// ---------------------------------------------------------------------------
// rbx MOJ arbiter: the problem's own testlib interactor, adapted in-process to
// MOJ's interactive protocol.
//
// MOJ's driver (mojtools/interactive/run.sh) runs `arbitro /tmp/in` between two
// FIFOs and reads the verdict from the LAST non-empty stderr line: `WRONG
// <reason>` is Wrong Answer, any other line is Accepted, and an arbiter that
// exits non-zero without a `WRONG` line is a judge error. A testlib interactor
// speaks exit codes instead. So testlib is built to THROW its exit code rather
// than call exit(), the interactor's `main` is renamed, and the `main` at the
// bottom of this file calls it and prints the verdict line.
//
// Generated by rbx -- do not edit by hand.
// ---------------------------------------------------------------------------
#define TESTLIB_THROW_EXIT_EXCEPTION_INSTEAD_OF_EXIT
#define main rbx_interactor_main
