import * as assert from 'assert';
import { test } from 'node:test';

import { ExpectationDisplay, expectationDisplay } from './expectation';

/**
 * Every member of `ExpectedOutcome`, with the display each one's `style()`,
 * `full_style()` and `icon()` produce, transcribed by hand from
 * rbx/box/schema.py as of 2026-08-19.
 *
 * Asserted as one whole table rather than member by member, because the
 * columns that are easiest to get wrong are the ones a spot check skips:
 * MEMORY_LIMIT_EXCEEDED sits between two `⧖` rows and Python decides its glyph
 * via `is_slow()`, which MLE fails. Pinning every column of every row is one
 * assertion and catches all of them.
 *
 * Note what this does *not* do: rbx growing a thirteenth member cannot fail a
 * list maintained by hand on this side. The new member would take the neutral
 * raw-label fallback, which is the designed graceful degradation -- so what
 * this table guards is a member being dropped or mistranscribed here, not rbx
 * moving underneath it. Re-check it against schema.py when bumping rbx.
 */
const EXPECTED: Record<string, ExpectationDisplay> = {
  ANY: { label: 'ANY', hue: 'neutral', bold: true, glyph: '?', badge: '?' },
  ACCEPTED: { label: 'AC', hue: 'green', bold: true, glyph: '✓', badge: '✓' },
  ACCEPTED_OR_TLE: {
    label: 'AC or TLE',
    hue: 'green',
    bold: false,
    glyph: '✓',
    badge: '✓⧖',
  },
  WRONG_ANSWER: {
    label: 'WA',
    hue: 'red',
    bold: false,
    glyph: '✗',
    badge: '✗',
  },
  INCORRECT: {
    label: 'INCORRECT',
    hue: 'red',
    bold: false,
    glyph: '✗',
    badge: '✗?',
  },
  RUNTIME_ERROR: {
    label: 'RTE',
    hue: 'blue',
    bold: false,
    glyph: '✗',
    badge: '✗!',
  },
  TIME_LIMIT_EXCEEDED: {
    label: 'TLE',
    hue: 'yellow',
    bold: false,
    glyph: '⧖',
    badge: '⧖',
  },
  MEMORY_LIMIT_EXCEEDED: {
    label: 'MLE',
    hue: 'yellow',
    bold: false,
    glyph: '✗',
    badge: '✗M',
  },
  OUTPUT_LIMIT_EXCEEDED: {
    label: 'OLE',
    hue: 'purple',
    bold: false,
    glyph: '✗',
    badge: '✗O',
  },
  TLE_OR_RTE: {
    label: 'TLE or RTE',
    hue: 'yellow',
    bold: false,
    glyph: '⧖',
    badge: '⧖!',
  },
  JUDGE_FAILED: {
    label: 'FL',
    hue: 'purple',
    bold: false,
    glyph: '✗',
    badge: '✗J',
  },
  COMPILATION_ERROR: {
    label: 'CE',
    hue: 'blue',
    bold: false,
    glyph: '✗',
    badge: '✗C',
  },
};

const MEMBERS = Object.keys(EXPECTED);

test('every ExpectedOutcome member is displayed exactly as rbx draws it', () => {
  const actual = Object.fromEntries(
    MEMBERS.map((member) => [member, expectationDisplay(member)]),
  );
  assert.deepStrictEqual(actual, EXPECTED);
});

test('nothing declared reads as undeclared, not as a display', () => {
  assert.strictEqual(expectationDisplay(undefined), undefined);
});


test('a member from a newer rbx still renders, labelled with its raw name', () => {
  assert.deepStrictEqual(expectationDisplay('PARTIALLY_ACCEPTED'), {
    label: 'PARTIALLY_ACCEPTED',
    hue: 'neutral',
    bold: false,
    glyph: '✗',
    badge: '✗',
  });
});

/**
 * The badge column is generated by two rules rather than chosen row by row, so
 * the rules are what these assert. A thirteenth member added to the table by
 * hand is only correct if it still satisfies all three.
 */
test('rule 1: a badge opens with the glyph rbx prints for the same expectation', () => {
  for (const member of MEMBERS) {
    const display = expectationDisplay(member);
    assert.ok(display !== undefined);
    assert.ok(
      display.badge.startsWith(display.glyph),
      `${member} badges ${display.badge}, which does not open with ${display.glyph}`,
    );
  }
});

test('rule 2: a badge is at most the two characters a FileDecoration renders', () => {
  for (const member of MEMBERS) {
    const display = expectationDisplay(member);
    assert.ok(display !== undefined);
    // Spread rather than `.length`: a future badge reaching for a glyph outside
    // the BMP would be two code units and one character, and it is characters
    // VS Code counts.
    assert.ok(
      [...display.badge].length <= 2,
      `${member} badges ${display.badge}, which is wider than two characters`,
    );
  }
});

/**
 * The point of the whole alphabet. Four members collide in pairs on colour --
 * ACCEPTED with ACCEPTED_OR_TLE, WRONG_ANSWER with INCORRECT -- and the badge
 * is the only channel left to separate them, since a `FileDecoration` has no
 * third dimension to spend. Asserting uniqueness across the whole table catches
 * a new member colliding with an old one as well.
 */
test('no two expectations are drawn with the same badge', () => {
  const seen = new Map<string, string>();
  for (const member of MEMBERS) {
    const badge = expectationDisplay(member)?.badge ?? '';
    const clash = seen.get(badge);
    assert.strictEqual(
      clash,
      undefined,
      `${member} and ${clash} would both badge as ${badge}`,
    );
    seen.set(badge, member);
  }
});

test('a name off Object.prototype is unknown, not whatever it inherits', () => {
  assert.deepStrictEqual(expectationDisplay('constructor'), {
    label: 'constructor',
    hue: 'neutral',
    bold: false,
    glyph: '✗',
    badge: '✗',
  });
});



