import math
import pathlib
import shutil
from typing import Dict, List, Optional, Set, Tuple

import typer
import yaml

from rbx import console, utils
from rbx.box import code, environment, header, limits_info, naming, package
from rbx.box.dependencies import graph as deps_graph
from rbx.box.dependencies.amalgamation import AmalgamationError, amalgamate
from rbx.box.formatting import href
from rbx.box.generation_schema import GenerationTestcaseEntry
from rbx.box.packaging import flattening
from rbx.box.packaging.domjudge.testlib_patch import patch_testlib_for_domjudge
from rbx.box.packaging.packager import BasePackager, BuiltStatement
from rbx.box.schema import CodeItem, ExpectedOutcome, Solution, TaskType
from rbx.box.statements.schema import Statement
from rbx.config import get_testlib
from rbx.grading.language_kind import LanguageKind

# DOMjudge `@EXPECTED_RESULTS@` verdict tokens (canonical hyphenated spelling).
# See SubmissionService::PROBLEM_RESULT_REMAP in DOMjudge.
_DJ_CORRECT = 'CORRECT'
_DJ_WRONG_ANSWER = 'WRONG-ANSWER'
_DJ_TIMELIMIT = 'TIMELIMIT'
_DJ_RUN_ERROR = 'RUN-ERROR'
_DJ_NO_OUTPUT = 'NO-OUTPUT'
_DJ_OUTPUT_LIMIT = 'OUTPUT-LIMIT'

# Every rbx outcome maps to the set of DOMjudge verdict tokens that satisfy it,
# so no solution is ever dropped from the package. DOMjudge has no memory-limit
# verdict (an over-memory run surfaces as RTE, sometimes TLE), so MLE is the one
# lossy mapping; everything else is exact. `ANY` lists every runtime verdict
# (anything but a compile error is acceptable).
_EXPECTED_RESULTS: Dict[ExpectedOutcome, List[str]] = {
    ExpectedOutcome.ACCEPTED: [_DJ_CORRECT],
    ExpectedOutcome.WRONG_ANSWER: [_DJ_WRONG_ANSWER],
    ExpectedOutcome.TIME_LIMIT_EXCEEDED: [_DJ_TIMELIMIT],
    ExpectedOutcome.RUNTIME_ERROR: [_DJ_RUN_ERROR],
    ExpectedOutcome.OUTPUT_LIMIT_EXCEEDED: [_DJ_OUTPUT_LIMIT],
    ExpectedOutcome.MEMORY_LIMIT_EXCEEDED: [_DJ_RUN_ERROR, _DJ_TIMELIMIT],
    ExpectedOutcome.ACCEPTED_OR_TLE: [_DJ_CORRECT, _DJ_TIMELIMIT],
    ExpectedOutcome.TLE_OR_RTE: [_DJ_TIMELIMIT, _DJ_RUN_ERROR],
    ExpectedOutcome.INCORRECT: [
        _DJ_WRONG_ANSWER,
        _DJ_RUN_ERROR,
        _DJ_TIMELIMIT,
        _DJ_OUTPUT_LIMIT,
        _DJ_NO_OUTPUT,
    ],
    ExpectedOutcome.ANY: [
        _DJ_CORRECT,
        _DJ_WRONG_ANSWER,
        _DJ_TIMELIMIT,
        _DJ_RUN_ERROR,
        _DJ_OUTPUT_LIMIT,
        _DJ_NO_OUTPUT,
    ],
}

# Single-verdict tokens that have a dedicated DOMjudge submission directory.
# DOMjudge derives the expected verdict from the directory name, so dropping a
# solution here needs no source annotation (and avoids a spurious import
# warning). `output_limit` is a DOMjudge extension over the 4 ICPC-spec dirs.
_STANDARD_DIRS: Dict[str, str] = {
    _DJ_CORRECT: 'accepted',
    _DJ_WRONG_ANSWER: 'wrong_answer',
    _DJ_TIMELIMIT: 'time_limit_exceeded',
    _DJ_RUN_ERROR: 'run_time_error',
    _DJ_OUTPUT_LIMIT: 'output_limit',
}

# Solutions whose expectation needs more than one verdict go here with an
# `@EXPECTED_RESULTS@` annotation. The directory name is deliberately NOT a
# verdict token: DOMjudge keeps the annotation verbatim (multiple acceptable
# verdicts) instead of collapsing it to the directory's single verdict.
_MIXED_DIR = 'mixed'

# Suffixes rbx knows how to reduce to a single translation unit. A solution in
# any other language has to already be one file.
_AMALGAMATABLE_SUFFIXES = {'.c', '.cc', '.cpp', '.cxx'}

# The same command DOMjudge's own auto-generated validator build uses, so a
# package that ships an explicit `build` compiles exactly as one that does not.
_VALIDATOR_CXX = 'g++ -Wall -O2 -std=gnu++20'

# The bridge that turns a legacy rbx interactor + checker pair into the single
# program DOMjudge runs. DOMjudge calls it as `<input> <answer> <feedbackdir>`
# with the submission's output on stdin and its input on stdout, so the
# interactor inherits the pipes untouched; the checker then grades the output
# the interactor wrote, exactly as rbx does locally. 42 is the validator
# protocol's accept code (see `testlib_patch`), so anything else is the
# interaction's own verdict and short-circuits the checker.
_LEGACY_RUN_SCRIPT = """\
#!/bin/sh
# Generated by rbx -- do not edit.
#
# DOMjudge's `runjury` contract: $0 <input> <answer> <feedbackdir>, with the
# submission's output on stdin and its input on stdout.

DIR=$(dirname "$0")
OUT=$(mktemp) || exit 1

"$DIR/interactor" "$1" "$OUT" "$2" "$3"
INTERACTOR_EXIT=$?

# Let go of the pipes to the submission, so it sees EOF while the checker runs
# instead of blocking until the wall clock kills it.
exec </dev/null >/dev/null

if [ "$INTERACTOR_EXIT" -ne 42 ]; then
    rm -f "$OUT"
    exit "$INTERACTOR_EXIT"
fi

"$DIR/checker" "$1" "$2" "$3" <"$OUT"
CHECKER_EXIT=$?
rm -f "$OUT"
exit "$CHECKER_EXIT"
"""


def _fmt_seconds(ms: int) -> str:
    """Format integer milliseconds as exact fractional seconds (no float rounding)."""
    return f'{ms // 1000}.{ms % 1000:03d}'


class DomjudgePackager(BasePackager):
    def __init__(
        self,
        testcase_entries: List[GenerationTestcaseEntry],
        language: Optional[str] = None,
    ):
        super().__init__(testcase_entries)
        self.language = language

    @classmethod
    def name(cls) -> str:
        return 'domjudge'

    @classmethod
    def task_types(cls) -> List[TaskType]:
        return [TaskType.BATCH, TaskType.COMMUNICATION]

    def languages(self) -> List[str]:
        if self.language is None:
            return super().languages()
        return [self.language]

    def _get_main_statement(self) -> Optional[Statement]:
        pkg = package.find_problem_package_or_die()
        if not pkg.expanded_statements:
            return None
        if self.language is None:
            return pkg.expanded_statements[0]
        for statement in pkg.expanded_statements:
            if statement.language == self.language:
                return statement
        return None

    def _get_main_built_statement(
        self, built_statements: List[BuiltStatement]
    ) -> Optional[BuiltStatement]:
        statement = self._get_main_statement()
        if statement is None:
            return None
        for built_statement in built_statements:
            if built_statement.statement == statement:
                return built_statement
        return None

    def _get_short_name(self) -> str:
        shortname = naming.get_problem_shortname_or_require()
        if shortname is not None:
            return shortname
        return package.find_problem_package_or_die().name

    def _get_color(self) -> Optional[str]:
        entry = naming.get_problem_entry_in_contest()
        if entry is None:
            return None
        _, problem = entry
        return problem.color

    def _get_ini(self) -> str:
        statement = self._get_main_statement()
        lang = statement.language if statement is not None else None
        title = naming.get_problem_title(lang, statement, fallback_to_title=True)
        limits = limits_info.get_limits(profile=self.name())
        assert limits.time is not None

        lines = [
            f'short-name = {self._get_short_name()}',
            f'name = {title.replace(chr(39), chr(96))}',
            f'timelimit = {_fmt_seconds(limits.time)}',
        ]
        color = self._get_color()
        if color is not None:
            lines.append(f'color = {color}')
        return '\n'.join(lines) + '\n'

    def _is_communication(self) -> bool:
        return package.find_problem_package_or_die().type == TaskType.COMMUNICATION

    def _get_problem_yaml(self) -> str:
        # rbx always ships its own judging program as a custom output validator
        # (below) -- the checker for a batch problem, the interactor for a
        # communication one -- so DOMjudge judges with exactly what rbx uses
        # locally instead of approximating it with a default validator.
        #
        # `custom interactive` is what flips DOMjudge into its combined
        # run/compare mode: the validator stops being the problem's compare
        # script and becomes its *run* script, wrapped in `runpipe` and driven
        # bidirectionally against the submission. That is DOMjudge's only shape
        # for interaction.
        pkg = package.find_problem_package_or_die()
        limits = limits_info.get_limits(profile=self.name())
        assert limits.memory is not None
        output_kb = limits.output if limits.output is not None else pkg.outputLimit

        data = {
            'limits': {
                'memory': limits.memory,
                'output': math.ceil(output_kb / 1024),
            },
            'validation': 'custom interactive'
            if self._is_communication()
            else 'custom',
        }
        return yaml.safe_dump(data, default_flow_style=False)

    def _require_cpp(self, item: CodeItem, role: str):
        if LanguageKind.CPP not in environment.language_kinds(code.find_language(item)):
            console.console.print(
                f'[error]DOMjudge packaging requires a C++ (testlib) {role}, '
                f'but found {href(item.path)}.[/error]'
            )
            raise typer.Exit(1)

    def _extra_translation_units(self, ns: flattening.FlatNamespace) -> List[str]:
        """Flat names of the dependencies that are translation units themselves.

        A header dependency is pulled in by the `#include` flattening already
        rewrote, but a dependency that is a `.cpp` of its own has to be named on
        the compiler's command line.
        """
        return sorted(
            file.flat_name
            for file in ns.dep_files()
            if pathlib.PurePath(file.flat_name).suffix.lower()
            in _AMALGAMATABLE_SUFFIXES
        )

    def _build_script(self, programs: List[Tuple[str, str]], extra: List[str]) -> str:
        """A `build` script compiling each `(source stem, program)` pair.

        rbx always writes one rather than leaning on DOMjudge's auto-detection,
        which compiles whichever source `readdir` happens to hand back first --
        harmless for a lone checker, wrong the moment a flattened dependency or
        a chained interactor puts a second source in the directory.
        """
        suffix = ''.join(f' {unit}' for unit in extra)
        lines = ['#!/bin/sh', '# Generated by rbx -- do not edit.', 'set -e', '']
        lines.extend(
            f'{_VALIDATOR_CXX} -o {program} {stem}.cpp{suffix}'
            for stem, program in programs
        )
        return '\n'.join(lines) + '\n'

    def _write_output_validators(self, into_path: pathlib.Path):
        # A modern rbx interactor is the sole judge of an interaction -- its
        # checker is the no-op builtin, and the schema forbids configuring
        # another one -- so it maps straight onto DOMjudge's single validator
        # program. A legacy interactor instead writes an output that a real
        # checker grades, so both have to ship and `run` chains them.
        # `get_interactor` refuses a communication package with no interactor
        # configured, which the schema does not itself forbid -- though the full
        # build `run_packager` does first would already have died on it.
        interactor = package.get_interactor() if self._is_communication() else None
        legacy = interactor is not None and interactor.legacy

        sources: List[CodeItem] = []
        reserved: Dict[pathlib.Path, str] = {}
        if interactor is not None:
            self._require_cpp(interactor, 'interactor')
            sources.append(interactor)
            reserved[package.get_relative_source_path(interactor)] = 'interactor.cpp'
        if interactor is None or legacy:
            checker = package.get_checker_or_builtin()
            self._require_cpp(checker, 'checker')
            sources.append(checker)
            reserved[package.get_relative_source_path(checker)] = 'checker.cpp'

        ns = flattening.build_flat_namespace(sources, reserved=reserved)

        into_path.mkdir(parents=True, exist_ok=True)
        ns.materialize(into_path)
        (into_path / 'testlib.h').write_text(
            patch_testlib_for_domjudge(get_testlib().read_text())
        )
        (into_path / 'rbx.h').write_text(header.get_header().read_text())

        extra = self._extra_translation_units(ns)
        if legacy:
            # `build` has to leave an executable `run` behind. DOMjudge renames
            # that to `runjury` and puts its own `runpipe` wrapper in its place.
            build = self._build_script(
                [('interactor', 'interactor'), ('checker', 'checker')], extra
            )
            build += (
                "\ncat > run <<'RBX_RUN_EOF'\n"
                + _LEGACY_RUN_SCRIPT
                + 'RBX_RUN_EOF\nchmod +x run\n'
            )
        else:
            stem = 'interactor' if interactor is not None else 'checker'
            build = self._build_script([(stem, 'run')], extra)

        build_path = into_path / 'build'
        build_path.write_text(build)
        build_path.chmod(0o755)

    def _write_testcases(self, data_path: pathlib.Path):
        sample_path = data_path / 'sample'
        secret_path = data_path / 'secret'
        sample_path.mkdir(parents=True, exist_ok=True)
        secret_path.mkdir(parents=True, exist_ok=True)

        counters = {True: 0, False: 0}
        for entry in self.get_built_testcase_entries():
            is_sample = entry.is_sample()
            dest_path = sample_path if is_sample else secret_path
            counters[is_sample] += 1
            index = counters[is_sample]

            testcase = entry.metadata.copied_to
            shutil.copyfile(testcase.inputPath, dest_path / f'{index:03d}.in')
            if testcase.outputPath is not None:
                shutil.copyfile(testcase.outputPath, dest_path / f'{index:03d}.ans')
            else:
                (dest_path / f'{index:03d}.ans').touch()

    def _expected_results(self, solution: Solution) -> List[str]:
        return _EXPECTED_RESULTS.get(
            solution.outcome, _EXPECTED_RESULTS[ExpectedOutcome.ANY]
        )

    def _comment_prefix(self, solution: Solution) -> str:
        kinds = environment.language_kinds(code.find_language(solution))
        return '#' if LanguageKind.PYTHON in kinds else '//'

    def _solution_content(self, solution: Solution) -> bytes:
        """The bytes to ship for a solution.

        DOMjudge compiles a jury solution exactly as it compiles a contestant's
        submission: from a single file. A C/C++ solution split across headers of
        its own is therefore amalgamated first -- shipped as-is it would build
        here and fail to compile on the judge.

        Resolution is deliberately left natural, with no `extra_roots`: a
        solution is contestant-like code, and the builtin headers rbx injects
        beside a source are tooling it has no business using. `rbx.h` reads a
        vars file the judge will not have, so inlining it would only turn a
        compile error into a runtime one; refusing names the header instead. Other languages have no
        amalgamator, so a multi-file closure is an error rather than a package
        whose submissions cannot build: `submissions/` holds one file per
        solution, so any dependency that resolves is one the judge will not have.
        """
        if solution.path.suffix.lower() in _AMALGAMATABLE_SUFFIXES:
            try:
                result = amalgamate(utils.abspath(solution.path))
            except AmalgamationError as e:
                console.console.print(
                    f'[error]Cannot package {solution.href()} for DOMjudge.[/error]\n'
                    f'[error]{e}[/error]\n'
                    '[error]DOMjudge compiles a submission from a single file, so it '
                    'must reduce to one self-contained translation unit.[/error]'
                )
                raise typer.Exit(1) from e
            return result.content

        # Deliberately unfiltered by dependency kind: an interpreted language
        # reports its imports as EXECUTION, not COMPILATION, so filtering on the
        # latter would let a Python solution importing a sibling module through
        # as a lone file that cannot run on the judge.
        graph = deps_graph.expand(solution)
        if graph is not None and len(graph.nodes) > 1:
            deps = ', '.join(
                str(path)
                for path in sorted(graph.nodes)
                if path != package.get_relative_source_path(solution)
            )
            console.console.print(
                f'[error]Cannot package {solution.href()} for DOMjudge: it depends on '
                f'[item]{deps}[/item], but DOMjudge builds a submission from a '
                'single file and rbx cannot amalgamate this language.[/error]'
            )
            raise typer.Exit(1)
        return solution.path.read_bytes()

    def _write_submissions(self, into_path: pathlib.Path):
        # DOMjudge auto-judges these on import and surfaces any verdict mismatch
        # on the jury "Judging verifier" page, so every rbx solution ships with a
        # faithful expectation. Single-verdict outcomes use the matching standard
        # directory; the rest go to `mixed/` with an `@EXPECTED_RESULTS@`
        # annotation listing every acceptable verdict.
        used_names: Set[str] = set()
        for solution in package.get_solutions():
            tokens = self._expected_results(solution)
            standard_dir = _STANDARD_DIRS.get(tokens[0]) if len(tokens) == 1 else None

            name = solution.path.name
            if name in used_names:
                name = '__'.join(solution.path.parts)
            used_names.add(name)

            content = self._solution_content(solution)

            if standard_dir is not None:
                dest_path = into_path / standard_dir / name
                dest_path.parent.mkdir(parents=True, exist_ok=True)
                dest_path.write_bytes(content)
                continue

            dest_path = into_path / _MIXED_DIR / name
            dest_path.parent.mkdir(parents=True, exist_ok=True)
            source = content.decode()
            if source and not source.endswith('\n'):
                source += '\n'
            annotation = (
                f'{self._comment_prefix(solution)} '
                f'@EXPECTED_RESULTS@: {", ".join(tokens)}\n'
            )
            dest_path.write_text(source + annotation)

    def package(
        self,
        build_path: pathlib.Path,
        into_path: pathlib.Path,
        built_statements: List[BuiltStatement],
    ) -> pathlib.Path:
        into_path.mkdir(parents=True, exist_ok=True)

        (into_path / 'domjudge-problem.ini').write_text(self._get_ini())
        (into_path / 'problem.yaml').write_text(self._get_problem_yaml())

        main_built_statement = self._get_main_built_statement(built_statements)
        if main_built_statement is not None:
            shutil.copyfile(main_built_statement.path, into_path / 'problem.pdf')

        self._write_testcases(into_path / 'data')

        # The rbx checker is always shipped as a custom output validator.
        self._write_output_validators(into_path / 'output_validators')

        self._write_submissions(into_path / 'submissions')

        # Zip all.
        shutil.make_archive(str(build_path / self.package_basename()), 'zip', into_path)

        return (build_path / self.package_basename()).with_suffix('.zip')
