#!/bin/bash
# Runs INSIDE the jail: jar in /tmp/dir (read-only), input /tmp/in, output /tmp/out.
exec &>/tmp/stderrlog
cd /tmp/dir
# binfile.sh is generated by build-and-test.sh and is the only channel carrying the
# problem's limits into the jail. It defines BIN, MOJ_MEMLIMITMB and MOJ_STACKKB.
source binfile.sh

# compile.sh named the entry point in the manifest, so no class election is needed
# here. JVM threads ignore the main thread's `ulimit -s`, so the problem's stack has
# to be mirrored into -Xss explicitly.
exec java -Xms10m -Xmx${MOJ_MEMLIMITMB:-500}m -Xss${MOJ_STACKKB:-131072}k \
     -jar "$BIN" < /tmp/in > /tmp/out
