# Whether to enable warnings when running solutions.
warnings:
  enabled: true

# A list of command substitutions to apply to rbx.
# Useful when replacing compilers in OS such as Mac.
command_substitutions:
  g++: g++
  gcc: gcc
  java: java
  javac: javac
  jar: jar
  python: python
  python2: python2
  python3: python3

caching:
  # Set the caching level.
  #
  # CACHE_ALL: Cache everything.
  # CACHE_COMPILATION: Cache only compilation.
  # NO_CACHE: Do not cache anything.
  level: CACHE_ALL

  # Whether to check the integrity of the cached result, and evict it
  # if file has changed since it was cached.
  #
  # Disable for more performance, but be careful to not modify any generated
  # files.
  check_integrity: true

repeats:
  # Number of times to run the solution.
  reps: 1
  # Number of times to retry if the solution TLs.
  retries: 0
  # Number of times to retry in stress mode if the solution TLs.
  retries_for_stress: 0

# Whether sanitizers will be enabled by default
# when running testlib components.
# This flag has no effect on running solutions with
# sanitizers. For this, you have to use the `-s` flag in `rbx run`.
sanitizers:
  enabled: false

  # A list of command substitutions to apply to rbx when
  # sanitizers are enabled.
  #
  # This is useful when replacing compilers in OS such as Mac,
  # since GCC on Mac does not support sanitizers.
  command_substitutions: {}
