#!/bin/bash
# Runs INSIDE the jail: binary in /tmp/dir (read-only), input /tmp/in, output /tmp/out.
exec &>/tmp/stderrlog
cd /tmp/dir
# binfile.sh is generated by build-and-test.sh and is the only channel carrying the
# problem's limits into the jail. It defines BIN, MOJ_MEMLIMITMB and MOJ_STACKKB.
source binfile.sh

# Quote every expansion of BIN: it carries the name the CONTESTANT submitted, which the
# judge materializes verbatim -- `l(1).cpp`, the mark a browser sticks on a repeated
# download, is a real report. Unquoted it reaches the shell raw and kills the run.

exec ./"$BIN" < /tmp/in > /tmp/out
