"""Render the static completion spec to a committed Python module.

Run: `mise run gen-completion-spec`. A drift test (drift_test.py) fails CI if the
committed module is out of date.
"""

import pprint
from pathlib import Path
from typing import Any, Dict

_HEADER = (
    '# GENERATED by `mise run gen-completion-spec` -- do not edit by hand.\n'
    '# Source of truth: the Typer app in rbx/box/cli.py.\n'
)


def _collect_completer_keys(spec: Dict[str, Any]) -> set:
    keys = set()
    for p in spec.get('params', []):
        v = p.get('value', {})
        if v.get('kind') == 'completer':
            keys.add(v['completer'])
    for child in spec.get('children', []):
        keys |= _collect_completer_keys(child)
    return keys


def build_payload() -> Dict[str, Any]:
    """Build the {SPEC, COMPLETERS} payload from the live Typer app."""
    import typer.main

    from rbx.box.cli import app
    from rbx.box.completion import (
        completers,  # noqa: F401  (registers completer keys)
        registry,
    )
    from rbx.box.completion.generate import build_spec

    spec = build_spec(typer.main.get_command(app), name='rbx')
    completer_paths = {}
    for key in sorted(_collect_completer_keys(spec)):
        # Reading the registry's private map from a sibling module in the same
        # package is intentional: the generator needs the dotted import paths.
        target = registry._REGISTRY.get(key)  # noqa: SLF001
        if isinstance(target, str):
            completer_paths[key] = target
        else:
            # A completer key with no importable dotted path can't be loaded on the
            # fast path; fail loudly so it gets fixed at generation time.
            raise RuntimeError(f'completer key {key!r} has no importable path')
    return {'SPEC': spec, 'COMPLETERS': completer_paths}


def render(payload: Dict[str, Any]) -> str:
    spec_str = pprint.pformat(payload['SPEC'], width=100, sort_dicts=True)
    completers_str = pprint.pformat(payload['COMPLETERS'], width=100, sort_dicts=True)
    return f'{_HEADER}\nSPEC = {spec_str}\n\nCOMPLETERS = {completers_str}\n'


def write_spec(out: Path) -> None:
    out.write_text(render(build_payload()))


if __name__ == '__main__':
    write_spec(Path(__file__).with_name('_spec.py'))
