/**
 * The Run view: solution -> group -> testcase.
 *
 * A custom TreeView rather than the VS Code Testing API (design D4). The Testing
 * API is shaped around *running* tests, which this extension deliberately never
 * does -- execution stays in the terminal, and rbx keeps sole ownership of it.
 */
import * as path from 'path';
import * as vscode from 'vscode';

import { discoverPackages, packageLabel } from './discovery';
import { PackageLayout } from './rbx/layout';
import { expectedShortName, isAccepted, matches, shortName } from './rbx/outcome';
import {
  ArtifactStore,
  GroupRun,
  RunReport,
  SolutionRun,
  TestcaseRun,
  groupOutcome,
  isComplete,
  solutionOutcome,
} from './rbx/store';

export type RunNode = PackageNode | SolutionNode | GroupNode | TestcaseNode;

export interface PackageNode {
  readonly kind: 'package';
  readonly pkg: PackageLayout;
}

export interface SolutionNode {
  readonly kind: 'solution';
  readonly pkg: PackageLayout;
  readonly run: SolutionRun;
}

export interface GroupNode {
  readonly kind: 'group';
  readonly pkg: PackageLayout;
  readonly run: SolutionRun;
  readonly group: GroupRun;
}

export interface TestcaseNode {
  readonly kind: 'testcase';
  readonly pkg: PackageLayout;
  readonly run: SolutionRun;
  readonly group: GroupRun;
  readonly testcase: TestcaseRun;
}

/** Milliseconds, from the seconds rbx records. */
function formatTime(seconds: number | undefined): string | undefined {
  if (seconds === undefined) {
    return undefined;
  }
  return `${Math.round(seconds * 1000)}ms`;
}

/** MiB, from the bytes rbx records. */
function formatMemory(bytes: number | undefined): string | undefined {
  if (bytes === undefined) {
    return undefined;
  }
  return `${Math.round(bytes / (1024 * 1024))}MB`;
}

function outcomeIcon(outcome: string | undefined): vscode.ThemeIcon {
  if (outcome === undefined) {
    // No evaluation on disk yet: either still running, or the run was
    // interrupted. Indistinguishable in v1; both read as pending.
    return new vscode.ThemeIcon('circle-outline');
  }
  if (outcome === 'accepted') {
    return new vscode.ThemeIcon('pass', new vscode.ThemeColor('testing.iconPassed'));
  }
  if (outcome === 'skipped') {
    return new vscode.ThemeIcon('debug-step-over', new vscode.ThemeColor('testing.iconSkipped'));
  }
  return new vscode.ThemeIcon('error', new vscode.ThemeColor('testing.iconFailed'));
}

function testcaseItem(node: TestcaseNode): vscode.TreeItem {
  const { testcase } = node;
  const evaluation = testcase.evaluation;
  const item = new vscode.TreeItem(
    testcase.stem,
    vscode.TreeItemCollapsibleState.None,
  );
  item.id = `${node.pkg.root}::${node.run.solution.index}::${node.group.name}::${testcase.stem}`;
  item.iconPath = outcomeIcon(evaluation?.outcome);
  item.contextValue = 'rbx.testcase';

  const parts = [shortName(evaluation?.outcome)];
  const time = formatTime(evaluation?.time);
  const memory = formatMemory(evaluation?.memory);
  if (time !== undefined) {
    parts.push(time);
  }
  if (memory !== undefined) {
    parts.push(memory);
  }
  if (evaluation?.message !== undefined && evaluation.message !== '') {
    parts.push(evaluation.message);
  }
  item.description = evaluation === undefined ? 'pending' : parts.join('  ');

  const tooltip = new vscode.MarkdownString();
  tooltip.appendMarkdown(`**${node.group.name}/${testcase.entry.index}** \`${testcase.stem}\`\n\n`);
  if (testcase.entry.generatorName !== undefined) {
    const args = testcase.entry.generatorArgs ?? '';
    tooltip.appendMarkdown(`Generated by \`${testcase.entry.generatorName} ${args}\`\n\n`);
  } else if (testcase.entry.copiedFrom !== undefined) {
    tooltip.appendMarkdown(`Copied from \`${testcase.entry.copiedFrom}\`\n\n`);
  }
  if (evaluation?.message !== undefined && evaluation.message !== '') {
    tooltip.appendMarkdown(`${evaluation.message}\n`);
  }
  item.tooltip = tooltip;

  // Single click opens the most useful artifact: the diff for a failure, the
  // input for anything else.
  item.command =
    evaluation !== undefined && !isAccepted(evaluation.outcome)
      ? { command: 'rbx.diffOutput', title: 'Diff Output', arguments: [node] }
      : { command: 'rbx.openInput', title: 'Open Input', arguments: [node] };

  return item;
}

function groupItem(node: GroupNode): vscode.TreeItem {
  const item = new vscode.TreeItem(
    node.group.name,
    vscode.TreeItemCollapsibleState.Expanded,
  );
  item.id = `${node.pkg.root}::${node.run.solution.index}::${node.group.name}`;
  item.contextValue = 'rbx.group';
  const outcome = groupOutcome(node.group);
  item.iconPath = outcomeIcon(outcome);
  const done = node.group.testcases.filter((t) => t.evaluation !== undefined).length;
  item.description =
    done === node.group.testcases.length
      ? shortName(outcome)
      : `${done}/${node.group.testcases.length}`;
  return item;
}

function solutionItem(node: SolutionNode): vscode.TreeItem {
  const { solution } = node.run;
  const item = new vscode.TreeItem(
    solution.path,
    vscode.TreeItemCollapsibleState.Expanded,
  );
  item.id = `${node.pkg.root}::${solution.index}`;
  item.contextValue = 'rbx.solution';
  item.resourceUri = vscode.Uri.file(path.join(node.pkg.root, solution.path));

  const outcome = solutionOutcome(node.run);
  item.iconPath = outcomeIcon(outcome);

  if (!isComplete(node.run)) {
    item.description = 'running…';
  } else if (outcome !== undefined && !matches(solution.expectedOutcome, outcome)) {
    // The headline finding of a run: a solution that did not behave as declared.
    item.description = `expected ${expectedShortName(solution.expectedOutcome)}, got ${shortName(outcome)}`;
  } else {
    item.description = shortName(outcome);
  }
  item.tooltip = `Expected ${expectedShortName(solution.expectedOutcome)}`;
  return item;
}

export class RunTreeProvider implements vscode.TreeDataProvider<RunNode> {
  private readonly changed = new vscode.EventEmitter<RunNode | undefined>();
  readonly onDidChangeTreeData = this.changed.event;

  private packages: PackageLayout[] = [];
  private readonly stores = new Map<string, ArtifactStore>();

  /** Reload everything: rediscover packages and drop all cached artifacts. */
  async refresh(): Promise<void> {
    this.packages = await discoverPackages();
    const roots = new Set(this.packages.map((pkg) => pkg.root));
    for (const root of this.stores.keys()) {
      if (!roots.has(root)) {
        this.stores.delete(root);
      }
    }
    for (const store of this.stores.values()) {
      store.invalidate();
    }
    this.changed.fire(undefined);
  }

  /** Drop cached artifacts for one package, in response to a filesystem event. */
  invalidate(root: string): void {
    this.stores.get(root)?.invalidate();
    this.changed.fire(undefined);
  }

  private storeFor(pkg: PackageLayout): ArtifactStore {
    let store = this.stores.get(pkg.root);
    if (store === undefined) {
      store = new ArtifactStore(pkg);
      this.stores.set(pkg.root, store);
    }
    return store;
  }

  report(pkg: PackageLayout): Promise<RunReport | undefined> {
    return this.storeFor(pkg).load();
  }

  getTreeItem(node: RunNode): vscode.TreeItem {
    switch (node.kind) {
      case 'package': {
        const item = new vscode.TreeItem(
          packageLabel(node.pkg),
          vscode.TreeItemCollapsibleState.Expanded,
        );
        item.id = node.pkg.root;
        item.contextValue = 'rbx.package';
        item.iconPath = new vscode.ThemeIcon('package');
        item.resourceUri = vscode.Uri.file(node.pkg.root);
        return item;
      }
      case 'solution':
        return solutionItem(node);
      case 'group':
        return groupItem(node);
      case 'testcase':
        return testcaseItem(node);
    }
  }

  async getChildren(node?: RunNode): Promise<RunNode[]> {
    if (node === undefined) {
      if (this.packages.length === 0) {
        await this.refresh();
      }
      // A single-problem workspace is the common case; skip the package level
      // entirely rather than making the user expand one node forever.
      if (this.packages.length === 1) {
        return this.solutionsOf(this.packages[0]);
      }
      return this.packages.map((pkg): PackageNode => ({ kind: 'package', pkg }));
    }

    switch (node.kind) {
      case 'package':
        return this.solutionsOf(node.pkg);
      case 'solution':
        return node.run.groups.map(
          (group): GroupNode => ({ kind: 'group', pkg: node.pkg, run: node.run, group }),
        );
      case 'group':
        return node.group.testcases.map(
          (testcase): TestcaseNode => ({
            kind: 'testcase',
            pkg: node.pkg,
            run: node.run,
            group: node.group,
            testcase,
          }),
        );
      case 'testcase':
        return [];
    }
  }

  private async solutionsOf(pkg: PackageLayout): Promise<SolutionNode[]> {
    const report = await this.report(pkg);
    if (report === undefined) {
      return [];
    }
    return report.solutions.map((run): SolutionNode => ({ kind: 'solution', pkg, run }));
  }
}
