/**
 * The Run view: solution -> group -> testcase.
 *
 * A custom TreeView rather than the VS Code Testing API (design D4). The Testing
 * API is shaped around *running* tests, which this extension deliberately never
 * does -- execution stays in the terminal, and rbx keeps sole ownership of it.
 */
import * as path from 'path';
import * as vscode from 'vscode';

import { groupUri } from './decorations';
import { discoverPackages, packageLabel } from './discovery';
import { log } from './log';
import { groupExpectation, solutionExpectation } from './rbx/expectation';
import { PackageLayout } from './rbx/layout';
import { expectedShortName, isAccepted, outcomeIcon, shortName } from './rbx/outcome';
import {
  ArtifactStore,
  GroupRun,
  PackageRun,
  SolutionRun,
  TestcaseRun,
} from './rbx/store';
import {
  Progress,
  formatCounts,
  formatMemory,
  formatScore,
  formatTime,
  groupDescription,
  progressOf,
  solutionDescription,
} from './rbx/summary';

export type RunNode = PackageNode | SolutionNode | GroupNode | TestcaseNode;

export interface PackageNode {
  readonly kind: 'package';
  readonly pkg: PackageLayout;
}

export interface SolutionNode {
  readonly kind: 'solution';
  readonly pkg: PackageLayout;
  readonly run: SolutionRun;
  /**
   * This package's run covered only this solution, so the user is focused on
   * it and the tree opens it. Mirrors how `rbx run` itself picks
   * `SingleSolutionRunReporter` -- the only reporter that prints per-testcase
   * lines -- on `len(skeleton.solutions) == 1`.
   */
  readonly solo: boolean;
}

export interface GroupNode {
  readonly kind: 'group';
  readonly pkg: PackageLayout;
  readonly run: SolutionRun;
  readonly group: GroupRun;
}

export interface TestcaseNode {
  readonly kind: 'testcase';
  readonly pkg: PackageLayout;
  readonly run: SolutionRun;
  readonly group: GroupRun;
  readonly testcase: TestcaseRun;
}

/**
 * The verdict's own icon, from the table in outcome.ts.
 *
 * Note this reads the *outcome*, not `matchesExpectation`: a solution declared
 * `WRONG_ANSWER` that answers wrongly is doing its job, and still gets the WA
 * icon. Whether that met the expectation is what the description and the
 * tooltip say -- same split the CLI makes, which also colors the verdict by
 * what happened rather than by whether it was wanted.
 */
function themeIconFor(outcome: string | undefined): vscode.ThemeIcon {
  const { icon, color } = outcomeIcon(outcome);
  return new vscode.ThemeIcon(icon, new vscode.ThemeColor(color));
}

function testcaseItem(node: TestcaseNode): vscode.TreeItem {
  const { testcase } = node;
  const evaluation = testcase.evaluation;
  const item = new vscode.TreeItem(
    testcase.stem,
    vscode.TreeItemCollapsibleState.None,
  );
  item.id = `${node.pkg.root}::${node.run.solution.index}::${node.group.name}::${testcase.stem}`;
  item.iconPath = themeIconFor(evaluation?.outcome);
  item.contextValue = 'rbx.testcase';

  const parts = [shortName(evaluation?.outcome)];
  const time = formatTime(evaluation?.time);
  const memory = formatMemory(evaluation?.memory);
  if (time !== undefined) {
    parts.push(time);
  }
  if (memory !== undefined) {
    parts.push(memory);
  }
  if (evaluation?.message !== undefined && evaluation.message !== '') {
    parts.push(evaluation.message);
  }
  item.description = evaluation === undefined ? 'pending' : parts.join(' · ');

  const tooltip = new vscode.MarkdownString();
  tooltip.appendMarkdown(`**${node.group.name}/${testcase.entry.index}** \`${testcase.stem}\`\n\n`);
  if (testcase.entry.generatorName !== undefined) {
    const args = testcase.entry.generatorArgs ?? '';
    tooltip.appendMarkdown(`Generated by \`${testcase.entry.generatorName} ${args}\`\n\n`);
  } else if (testcase.entry.copiedFrom !== undefined) {
    tooltip.appendMarkdown(`Copied from \`${testcase.entry.copiedFrom}\`\n\n`);
  }
  if (evaluation?.message !== undefined && evaluation.message !== '') {
    tooltip.appendMarkdown(`${evaluation.message}\n`);
  }
  item.tooltip = tooltip;

  // Single click opens the most useful artifact: the diff for a failure, the
  // input for anything else.
  item.command =
    evaluation !== undefined && !isAccepted(evaluation.outcome)
      ? { command: 'rbx.diffOutput', title: 'Diff Output', arguments: [node] }
      : { command: 'rbx.openInput', title: 'Open Input', arguments: [node] };

  return item;
}

/**
 * The aggregate tooltip lines, from rbx's report.
 *
 * `aggregates` is absent until the solution finishes -- rbx publishes the
 * report per solution -- so mid-run the tooltip says how far it has got and
 * nothing about verdicts.
 */
function appendSummary(
  tooltip: vscode.MarkdownString,
  aggregates:
    | {
        outcome?: string;
        score: number;
        maxScore: number;
        maxTime?: number;
        maxMemory?: number;
      }
    | undefined,
  progress: Progress,
  testcases: readonly TestcaseRun[],
): void {
  if (aggregates === undefined) {
    tooltip.appendMarkdown(`Still running: ${progress.done}/${progress.total} tests\n`);
    return;
  }
  tooltip.appendMarkdown(`Verdict: **${shortName(aggregates.outcome)}**\n\n`);
  if (aggregates.maxScore > 0) {
    tooltip.appendMarkdown(
      `Score: ${formatScore(aggregates.score, aggregates.maxScore)}\n\n`,
    );
  }
  tooltip.appendMarkdown(`Tests: ${progress.done}/${progress.total}`);
  const counts = formatCounts(testcases);
  if (counts !== '') {
    tooltip.appendMarkdown(` (${counts})`);
  }
  tooltip.appendMarkdown('\n\n');
  // Max, not total: the slowest test is what the time limit is judged against.
  tooltip.appendMarkdown(`Max time: ${formatTime(aggregates.maxTime) ?? '-'}\n\n`);
  tooltip.appendMarkdown(`Max memory: ${formatMemory(aggregates.maxMemory) ?? '-'}\n`);
}

function groupItem(node: GroupNode): vscode.TreeItem {
  // Groups stay expanded even under a collapsed solution: collapsing them too
  // would put two clicks between the user and any testcase, and the group
  // breakdown is the reason to open a solution at all.
  const item = new vscode.TreeItem(
    node.group.name,
    vscode.TreeItemCollapsibleState.Expanded,
  );
  item.id = `${node.pkg.root}::${node.run.solution.index}::${node.group.name}`;
  item.contextValue = 'rbx.group';
  // A group has no file, so it gets a synthetic URI purely to be addressable by
  // the decoration provider. Set unconditionally: the provider returns nothing
  // for a group that declared no expectation of its own.
  item.resourceUri = groupUri(node.pkg, node.run.solution.index, node.group.name);

  const report = node.group.report;
  const progress = progressOf(node.group.testcases);
  item.iconPath = themeIconFor(report?.outcome);
  item.description = groupDescription(report, progress);

  const tooltip = new vscode.MarkdownString();
  tooltip.appendMarkdown(`**${node.group.name}**\n\n`);
  const expectation = groupExpectation(node.group);
  if (expectation !== undefined) {
    tooltip.appendMarkdown(
      expectation.status === 'missed'
        ? `**Missed its expectation**: ${expectedShortName(expectation.declared)}\n\n`
        : `Expected: ${expectedShortName(expectation.declared)}\n\n`,
    );
  }
  appendSummary(tooltip, report, progress, node.group.testcases);
  item.tooltip = tooltip;
  return item;
}

function solutionItem(node: SolutionNode): vscode.TreeItem {
  const { solution } = node.run;
  const item = new vscode.TreeItem(
    solution.path,
    node.solo
      ? vscode.TreeItemCollapsibleState.Expanded
      : vscode.TreeItemCollapsibleState.Collapsed,
  );
  item.id = `${node.pkg.root}::${solution.index}`;
  item.resourceUri = vscode.Uri.file(path.join(node.pkg.root, solution.path));

  const report = node.run.report;
  const expectation = solutionExpectation(node.run);
  // Suffixed rather than replaced: the existing menu `when` clauses match
  // `viewItem` by prefix regex, so they keep applying to a mismatched row.
  item.contextValue =
    expectation?.status === 'missed' ? 'rbx.solution.mismatch' : 'rbx.solution';
  const testcases = node.run.groups.flatMap((group) => group.testcases);
  const progress = progressOf(testcases);
  item.iconPath = themeIconFor(report?.outcome);
  item.description = solutionDescription(report, progress, solution.expectedOutcome);

  const tooltip = new vscode.MarkdownString();
  tooltip.appendMarkdown(`**${solution.path}**\n\n`);
  // The skeleton's declared expectation, which is there even before the report.
  tooltip.appendMarkdown(
    expectation?.status === 'missed'
      ? `**Missed its expectation**: ${expectedShortName(solution.expectedOutcome)}\n\n`
      : `Expected: ${expectedShortName(solution.expectedOutcome)}\n\n`,
  );
  appendSummary(tooltip, report, progress, testcases);
  // rbx names the groups that missed their own expectation; which layer caught
  // the solution -- pooled or per-group -- is its call, already made.
  if (report !== undefined && report.failedGroups.length > 0) {
    tooltip.appendMarkdown(`\nFailing groups: ${report.failedGroups.join(', ')}\n`);
  }
  item.tooltip = tooltip;
  return item;
}

export class RunTreeProvider implements vscode.TreeDataProvider<RunNode> {
  private readonly changed = new vscode.EventEmitter<RunNode | undefined>();
  readonly onDidChangeTreeData = this.changed.event;

  private packages: PackageLayout[] = [];
  private readonly stores = new Map<string, ArtifactStore>();
  /**
   * In-flight or completed discovery.
   *
   * Discovery must be tracked explicitly rather than inferred from
   * `packages.length`: a workspace with no rbx package is a legitimate steady
   * state, and re-running discovery whenever the list is empty would have
   * `getChildren` fire the change event, which makes VS Code call `getChildren`
   * again -- an endless loop behind a permanently empty view.
   */
  private discovery?: Promise<void>;

  /** Reload everything: rediscover packages and drop all cached artifacts. */
  async refresh(): Promise<void> {
    this.discovery = this.discover();
    await this.discovery;
    this.changed.fire(undefined);
  }

  private async ensureDiscovered(): Promise<void> {
    if (this.discovery === undefined) {
      this.discovery = this.discover();
    }
    await this.discovery;
  }

  private async discover(): Promise<void> {
    this.packages = await discoverPackages();
    log(
      this.packages.length === 0
        ? 'No problem.rbx.yml found in the workspace.'
        : `Found ${this.packages.length} package(s): ${this.packages.map((p) => p.root).join(', ')}`,
    );
    const roots = new Set(this.packages.map((pkg) => pkg.root));
    for (const root of this.stores.keys()) {
      if (!roots.has(root)) {
        this.stores.delete(root);
      }
    }
    for (const store of this.stores.values()) {
      store.invalidate();
    }
  }

  /** Drop cached artifacts for one package, in response to a filesystem event. */
  invalidate(root: string): void {
    this.stores.get(root)?.invalidate();
    this.changed.fire(undefined);
  }

  private storeFor(pkg: PackageLayout): ArtifactStore {
    let store = this.stores.get(pkg.root);
    if (store === undefined) {
      store = new ArtifactStore(pkg);
      this.stores.set(pkg.root, store);
    }
    return store;
  }

  report(pkg: PackageLayout): Promise<PackageRun | undefined> {
    return this.storeFor(pkg).load();
  }

  /** Packages discovered so far. For the decoration provider, which is addressed
   * by URI and so has to map one back to the package that owns it. */
  knownPackages(): readonly PackageLayout[] {
    return this.packages;
  }

  getTreeItem(node: RunNode): vscode.TreeItem {
    switch (node.kind) {
      case 'package': {
        const item = new vscode.TreeItem(
          packageLabel(node.pkg),
          vscode.TreeItemCollapsibleState.Expanded,
        );
        item.id = node.pkg.root;
        item.contextValue = 'rbx.package';
        item.iconPath = new vscode.ThemeIcon('package');
        item.resourceUri = vscode.Uri.file(node.pkg.root);
        return item;
      }
      case 'solution':
        return solutionItem(node);
      case 'group':
        return groupItem(node);
      case 'testcase':
        return testcaseItem(node);
    }
  }

  async getChildren(node?: RunNode): Promise<RunNode[]> {
    if (node === undefined) {
      await this.ensureDiscovered();
      // A single-problem workspace is the common case; skip the package level
      // entirely rather than making the user expand one node forever.
      if (this.packages.length === 1) {
        return this.solutionsOf(this.packages[0]);
      }
      return this.packages.map((pkg): PackageNode => ({ kind: 'package', pkg }));
    }

    switch (node.kind) {
      case 'package':
        return this.solutionsOf(node.pkg);
      case 'solution':
        return node.run.groups.map(
          (group): GroupNode => ({ kind: 'group', pkg: node.pkg, run: node.run, group }),
        );
      case 'group':
        return node.group.testcases.map(
          (testcase): TestcaseNode => ({
            kind: 'testcase',
            pkg: node.pkg,
            run: node.run,
            group: node.group,
            testcase,
          }),
        );
      case 'testcase':
        return [];
    }
  }

  private async solutionsOf(pkg: PackageLayout): Promise<SolutionNode[]> {
    const report = await this.report(pkg);
    if (report === undefined) {
      log(`No readable run for ${pkg.root} -- run \`rbx run\` in that directory.`);
      return [];
    }
    log(`${pkg.root}: ${report.solutions.length} solution(s) in the last run.`);
    const solo = report.solutions.length === 1;
    return report.solutions.map((run): SolutionNode => ({ kind: 'solution', pkg, run, solo }));
  }
}
