/**
 * The `rbx: Testset` panel's HTML, as a pure function of the view model.
 *
 * Everything here is a *painting* decision: which element a gallery cell is,
 * which `hue-*` class a coverage tick carries, which column a stat lands in.
 * Whether a `.dat` can be shown as a picture, whether a variable was ever hit,
 * what a group's testcases add up to -- all decided in panelViewModel.ts, and
 * not reopened here.
 *
 * No `vscode` import and no DOM, exactly as render.ts: a string in, a string
 * out, so `node --test` holds the markup to account. The one thing the model
 * cannot carry is a `webview.asWebviewUri`, so the host resolves those and
 * hands them in as `PanelAssets` -- a cell whose id is missing from that map is
 * a file the manifest named and that is no longer on disk, and it draws a
 * placeholder rather than a broken image.
 *
 * `escapeHtml`/`escapeAttr` come from render.ts rather than being written
 * again: two escapers in one webview bundle is one of them going stale.
 *
 * Note that panelViewModel.ts is imported for its *types only*, and must stay
 * that way: it reaches `testset.ts` and through it `model.ts`, which imports
 * Node's `path` -- fine in the host bundle, unresolvable in the browser one.
 * That is also why the one filter the gallery needs lives here rather than
 * being pulled across as a value.
 */
import type {
  Coverage,
  Gallery,
  GalleryCell,
  PanelUiState,
  PanelViewModel,
  Stats,
} from '../rbx/panelViewModel';
import { escapeAttr, escapeHtml } from './render';

/** The cells of one group, or every cell when no group is picked. */
export function visibleCells(gallery: Gallery, group?: string): readonly GalleryCell[] {
  return group === undefined
    ? gallery.cells
    : gallery.cells.filter((cell) => cell.group === group);
}

/**
 * Webview URIs for the visualizations that actually exist, by cell id.
 *
 * Resolved by the host because `asWebviewUri` needs the `Webview` and the
 * package root, neither of which crosses into a pure module. Absent means
 * "checked, and not there".
 */
export type PanelAssets = Readonly<Record<string, string>>;

const TABS: readonly { readonly id: PanelUiState['tab']; readonly label: string }[] = [
  { id: 'gallery', label: 'Visualizations' },
  { id: 'coverage', label: 'Coverage' },
  { id: 'stats', label: 'Stats' },
];

function codicon(name: string): string {
  return `<span class="codicon codicon-${name}"></span>`;
}

/**
 * The tab strip, plus the group picker.
 *
 * The picker sits in the strip rather than inside the gallery even though only
 * the gallery reads it, so that switching tabs does not move the controls under
 * the pointer. It is disabled, not hidden, on the tabs that ignore it -- a
 * control that vanishes reads as a bug.
 */
export function renderTabs(model: PanelViewModel, state: PanelUiState): string {
  const tabs = TABS.map((tab) => {
    const current = tab.id === state.tab;
    return (
      `<button class="tab${current ? ' tab-current' : ''}" role="tab" ` +
      `aria-selected="${current}" data-tab="${escapeAttr(tab.id)}">` +
      `${escapeHtml(tab.label)}</button>`
    );
  }).join('');
  const options = ['<option value="">All groups</option>']
    .concat(
      model.groups.map(
        (group) =>
          `<option value="${escapeAttr(group)}"${group === state.group ? ' selected' : ''}>` +
          `${escapeHtml(group)}</option>`,
      ),
    )
    .join('');
  const disabled = state.tab === 'gallery' ? '' : ' disabled';
  return (
    `<div class="tabs" role="tablist">${tabs}` +
    `<span class="tabs-spacer"></span>` +
    `<select id="group" class="group-picker" aria-label="Group"${disabled}>${options}</select>` +
    `</div>`
  );
}

/** The picture, the `<iframe>`, or the offer -- never a guess. */
function galleryFigure(cell: GalleryCell, assets: PanelAssets): string {
  const src = assets[cell.id];
  if (src === undefined) {
    // Named by the manifest, gone from disk: the build was cleaned, or the
    // visualizer was removed and the manifest not rewritten. Saying so beats a
    // broken-image glyph, which reads as the extension failing.
    return (
      `<div class="cell-missing" title="${escapeAttr(cell.path)}">` +
      `${codicon('file-binary')}<span>missing</span></div>`
    );
  }
  switch (cell.kind) {
    case 'image':
      // `loading="lazy"`: a gallery is hundreds of files and only a screenful
      // of them is ever on screen.
      return (
        `<img class="cell-image" loading="lazy" src="${escapeAttr(src)}" ` +
        `alt="${escapeAttr(`${cell.stem} ${cell.channel} visualization`)}">`
      );
    case 'html':
      // `sandbox=""` and nothing else: a visualizer's HTML is generated by a
      // program in the package, and it gets no script execution, no forms and
      // no same-origin access to the panel. Anything it needs beyond that, the
      // setter opens in an editor.
      return (
        `<iframe class="cell-frame" sandbox="" loading="lazy" ` +
        `src="${escapeAttr(src)}" title="${escapeAttr(cell.path)}"></iframe>`
      );
    case 'other':
      return (
        `<button class="cell-open" data-open="${escapeAttr(cell.id)}" ` +
        `title="${escapeAttr(cell.path)}">${codicon('go-to-file')}` +
        `<span>Open .${escapeHtml(cell.extension || 'file')} in editor</span></button>`
      );
  }
}

export function renderGallery(
  model: PanelViewModel,
  state: PanelUiState,
  assets: PanelAssets,
): string {
  const cells = visibleCells(model.gallery, state.group);
  if (cells.length === 0) {
    const scope = state.group === undefined ? 'this testset' : `group ${state.group}`;
    return (
      `<p class="empty">No visualizations in ${escapeHtml(scope)}. ` +
      `Declare a <code>visualizer</code> in <code>problem.rbx.yml</code> and rebuild.</p>`
    );
  }
  const figures = cells
    .map((cell) => {
      // The whole cell is clickable and the caption states which testcase it
      // is, so a gallery scanned at a glance still answers "which test is
      // this" without a hover.
      const channel = cell.channel === 'output' ? ' <span class="cell-channel">out</span>' : '';
      return (
        `<figure class="cell" data-id="${escapeAttr(cell.id)}" tabindex="0" ` +
        `data-group="${escapeAttr(cell.group)}">` +
        `${galleryFigure(cell, assets)}` +
        `<figcaption class="cell-label">${escapeHtml(cell.label)}${channel}</figcaption>` +
        `</figure>`
      );
    })
    .join('');
  const hidden =
    model.gallery.withoutVisualization === 0
      ? ''
      : `<p class="note">${model.gallery.withoutVisualization} testcase(s) produced no visualization.</p>`;
  return `${hidden}<div class="gallery">${figures}</div>`;
}

/** One cell's two ticks: min on the left, max on the right, always both. */
function coverageTicks(minHit: boolean, maxHit: boolean): string {
  const tick = (hit: boolean, bound: string): string =>
    `<span class="tick" title="${escapeAttr(`${bound} ${hit ? 'hit' : 'not hit'}`)}">` +
    `${codicon(hit ? 'pass-filled' : 'circle-large-outline')}</span>`;
  return `${tick(minHit, 'min')}${tick(maxHit, 'max')}`;
}

export function renderCoverage(coverage: Coverage): string {
  if (!coverage.reported) {
    // The one case an empty table would lie about: `-v0` never computed this,
    // which is not the same as "validated and nothing was hit".
    return (
      `<p class="empty">This build ran without validation (<code>-v0</code>), so no ` +
      `constraint coverage was computed. Rebuild without <code>-v0</code> to see which ` +
      `bounds the testset reaches.</p>`
    );
  }
  if (coverage.rows.length === 0) {
    return `<p class="empty">The validator reported no bounded variables.</p>`;
  }
  const rollup =
    coverage.neverHit.length === 0
      ? `<p class="rollup rollup-clear">${codicon('pass')} Every variable reaches a bound somewhere.</p>`
      : `<p class="rollup rollup-warn">${codicon('warning')} Never hit at either bound: ` +
        `${coverage.neverHit.map((name) => `<code>${escapeHtml(name)}</code>`).join(', ')}</p>`;
  const head = coverage.groups
    .map((group, column) => {
      const validator = coverage.validators[column];
      const title = validator === undefined ? '' : ` title="${escapeAttr(validator)}"`;
      return `<th scope="col"${title}>${escapeHtml(group)}</th>`;
    })
    .join('');
  const body = coverage.rows
    .map((row) => {
      const cells = row.cells
        .map((cell) => {
          if (cell === undefined) {
            return `<td class="cell-none">&mdash;</td>`;
          }
          const value =
            cell.value === undefined
              ? ''
              : `<span class="cell-value">${escapeHtml(cell.value)}</span>`;
          return (
            `<td class="hue-${cell.hue}">${coverageTicks(cell.minHit, cell.maxHit)}${value}</td>`
          );
        })
        .join('');
      return `<tr><th scope="row"><code>${escapeHtml(row.variable)}</code></th>${cells}</tr>`;
    })
    .join('');
  return (
    `${rollup}<div class="table-scroll"><table class="coverage">` +
    `<thead><tr><th scope="col">Variable</th>${head}</tr></thead>` +
    `<tbody>${body}</tbody></table></div>`
  );
}

function cellText(text: string | undefined): string {
  return text === undefined ? '<span class="cell-none">&mdash;</span>' : escapeHtml(text);
}

export function renderStats(model: PanelViewModel): string {
  const stats: Stats = model.stats;
  if (stats.groups.length === 0) {
    return `<p class="empty">This testset has no groups.</p>`;
  }
  const rows = stats.groups
    .map((group) => {
      const subgroups =
        group.subgroups.length === 0
          ? '<span class="cell-none">&mdash;</span>'
          : group.subgroups
              .map(
                (subgroup) =>
                  `<span class="chip">${escapeHtml(subgroup.name)} ${subgroup.count}</span>`,
              )
              .join(' ');
      const deps =
        group.deps.length === 0
          ? '<span class="cell-none">&mdash;</span>'
          : group.deps.map((dep) => `<code>${escapeHtml(dep)}</code>`).join(', ');
      return (
        `<tr><th scope="row">${escapeHtml(group.group)}</th>` +
        `<td class="num">${group.count}</td>` +
        `<td class="num">${cellText(group.score)}</td>` +
        `<td>${deps}</td><td>${subgroups}</td>` +
        `<td class="num">${cellText(group.maxInput)}</td>` +
        `<td class="num">${cellText(group.totalInput)}</td>` +
        `<td class="num">${cellText(group.maxOutput)}</td></tr>`
      );
    })
    .join('');
  // The totals row is inside the same table rather than a separate summary
  // block, so every number in a column is read against the same header.
  const totals =
    `<tr class="totals"><th scope="row">Total</th>` +
    `<td class="num">${stats.count}</td><td class="num"></td><td></td>` +
    `<td>${stats.samples} sample(s)</td>` +
    `<td class="num">${cellText(stats.maxInput)}</td>` +
    `<td class="num">${cellText(stats.totalInput)}</td>` +
    `<td class="num">${cellText(stats.maxOutput)}</td></tr>`;
  const taskType =
    model.taskType === undefined
      ? ''
      : `<p class="note">Task type: <code>${escapeHtml(model.taskType)}</code></p>`;
  return (
    `${taskType}<div class="table-scroll"><table class="stats">` +
    `<thead><tr><th scope="col">Group</th><th scope="col">Tests</th>` +
    `<th scope="col">Score</th><th scope="col">Deps</th><th scope="col">Subgroups</th>` +
    `<th scope="col">Max in</th><th scope="col">Total in</th><th scope="col">Max out</th>` +
    `</tr></thead><tbody>${rows}${totals}</tbody></table></div>`
  );
}

/**
 * The whole panel body: the tab strip and whichever tab is showing.
 *
 * One string rather than one call per region, unlike the sidebar's renderer:
 * the panel has no focus to preserve across a re-render (its rows are not a
 * roving tabindex) and no independently scrolling sub-region, so replacing the
 * body wholesale is both simpler and indistinguishable on screen.
 */
export function renderPanel(
  model: PanelViewModel,
  state: PanelUiState,
  assets: PanelAssets,
): string {
  if (model.empty) {
    return (
      `<p class="empty">No testset manifest in this package. Run <code>rbx build</code> ` +
      `to publish one at <code>build/testset.yml</code>.</p>`
    );
  }
  const body = (): string => {
    switch (state.tab) {
      case 'gallery':
        return renderGallery(model, state, assets);
      case 'coverage':
        return renderCoverage(model.coverage);
      case 'stats':
        return renderStats(model);
    }
  };
  return `${renderTabs(model, state)}<div class="tab-body" role="tabpanel">${body()}</div>`;
}
