import * as assert from 'assert';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { test } from 'node:test';

import type { TestsetRow, TestsetViewModel } from '../rbx/testsetViewModel';
import {
  TestsetUiState,
  matchesTestsetFilter,
  renderTestsetCard,
  renderTestsetHeader,
  renderTestsetTree,
  visibleTestsetRows,
} from './testsetRender';

// The fixtures are written as rows rather than run through
// `buildTestsetViewModel`: the renderer's contract is the row, and building one
// from a manifest would make these tests fail for reasons that belong to
// testsetViewModel.test.ts.

function row(over: Partial<TestsetRow> & Pick<TestsetRow, 'id'>): TestsetRow {
  return {
    depth: 0,
    kind: 'group',
    label: over.id,
    meta: [],
    flags: [],
    expandable: false,
    defaultExpanded: false,
    search: (over.label ?? over.id).toLowerCase(),
    section: 'rbx.testsetGroup',
    ...over,
  };
}

function model(rows: readonly TestsetRow[]): TestsetViewModel {
  return { rows, empty: false, header: { built: 'built 3m ago', summary: '2 tests · 1 group' } };
}

function state(over: Partial<TestsetUiState> = {}): TestsetUiState {
  return { expanded: new Set<string>(), filter: '', ...over };
}

const MAIN = row({
  id: 'main',
  kind: 'group',
  label: 'main',
  meta: [
    { text: '[60/100]', hue: 'dim', role: 'score' },
    { text: '2 tests', hue: 'dim', role: 'count' },
  ],
  expandable: true,
  defaultExpanded: true,
});

const CASE = row({
  id: 'main::1-gen-000',
  parentId: 'main',
  depth: 1,
  kind: 'testcase',
  label: '1-gen-000',
  meta: [{ text: '4 KiB', hue: 'dim', role: 'size' }],
  flags: [{ kind: 'visualization', hue: 'blue', title: 'Has a visualization' }],
  search: 'main/1-gen-000 gen 1000',
  section: 'rbx.testsetTestcase',
  primaryCommand: 'rbx.openBuiltTestcase',
  card: {
    title: 'main/1-gen-000',
    origins: [{ text: 'gen 1000 7', title: 'Generated by gen 1000 7' }],
    values: [{ label: 'Input', text: '4 KiB' }],
    visualization: 'build/tests/main/visualization/1-gen-000.svg',
    lazyVisualizers: { input: false, output: false },
  },
});

const REJECTED = row({
  id: 'main::1-gen-001',
  parentId: 'main',
  depth: 1,
  kind: 'testcase',
  label: '1-gen-001',
  flags: [{ kind: 'invalid', hue: 'red', title: 'n must be at most 100' }],
  search: 'main/1-gen-001 invalid',
  section: 'rbx.testsetTestcase',
  primaryCommand: 'rbx.openBuiltTestcase',
  card: {
    title: 'main/1-gen-001',
    origins: [],
    values: [],
    lazyVisualizers: { input: false, output: false },
    validation: {
      ok: false,
      hue: 'red',
      text: 'Rejected by the validator',
      validator: 'validator.cpp',
      message: 'n must be at most 100',
    },
  },
});

const TREE = model([MAIN, CASE, REJECTED]);
const OPEN = state({ expanded: new Set(['main']) });

test('a group row is a tree item with a twisty, a meta line and a marks cell', () => {
  const html = renderTestsetTree(TREE, OPEN);
  assert.ok(html.includes('class="row testset-row kind-group"'), html);
  assert.ok(html.includes('<span class="twisty codicon codicon-chevron-down"></span>'), html);
  assert.ok(html.includes('<span class="span span-score hue-dim">[60/100]</span>'), html);
  assert.ok(html.includes('<span class="span span-count hue-dim">2 tests</span>'), html);
  // The marks cell exists on every row, empty or not, so the column can be
  // scanned straight down.
  assert.strictEqual(html.match(/class="flags"/g)?.length, 3);
});

test('the separators are drawn by the stylesheet, never emitted between spans', () => {
  const html = renderTestsetTree(TREE, OPEN);
  assert.ok(html.includes('[60/100]</span><span class="span span-count'), html);
});

test('a mark carries its own hue and its reason as the hover', () => {
  const html = renderTestsetTree(TREE, OPEN);
  assert.ok(
    html.includes(
      '<span class="flag flag-visualization hue-blue" title="Has a visualization">' +
        '<span class="codicon codicon-file-media"></span></span>',
    ),
    html,
  );
  assert.ok(
    html.includes(
      '<span class="flag flag-invalid hue-red" title="n must be at most 100">' +
        '<span class="codicon codicon-warning"></span></span>',
    ),
    html,
  );
});

test('every row announces its place in the tree, and only parents announce expansion', () => {
  const html = renderTestsetTree(TREE, OPEN);
  assert.ok(html.includes('aria-level="1" aria-setsize="1" aria-posinset="1"'), html);
  assert.ok(html.includes('aria-level="2" aria-setsize="2" aria-posinset="2"'), html);
  // Absent, not false, on a leaf: `aria-expanded="false"` on a childless node
  // tells a screen reader there is something to open.
  assert.strictEqual(html.match(/aria-expanded/g)?.length, 1);
});

test('exactly one row holds the tab stop', () => {
  const html = renderTestsetTree(TREE, state({ expanded: new Set(['main']), selected: CASE.id }));
  assert.strictEqual(html.match(/tabindex="0"/g)?.length, 1);
  assert.ok(html.includes(`data-id="main::1-gen-000"`), html);
  // With nothing selected the first row stands in, so a Tab into the view lands
  // somewhere useful.
  assert.ok(renderTestsetTree(TREE, OPEN).indexOf('tabindex="0"') < 200);
});

test('a row carries the section its context menu keys on', () => {
  const html = renderTestsetTree(TREE, OPEN);
  assert.ok(html.includes('&quot;webviewSection&quot;:&quot;rbx.testsetGroup&quot;'), html);
  assert.ok(html.includes('&quot;webviewSection&quot;:&quot;rbx.testsetTestcase&quot;'), html);
  assert.ok(html.includes('&quot;preventDefaultContextMenuItems&quot;:true'), html);
});

test('a collapsed group hides its tests', () => {
  const html = renderTestsetTree(TREE, state());
  assert.ok(html.includes('data-id="main"'), html);
  assert.ok(!html.includes('1-gen-000'), html);
});

test('a filter keeps the group of a matching test, and the tests of a matching group', () => {
  const byStem = visibleTestsetRows(TREE, state({ expanded: new Set(['main']), filter: '001' }));
  assert.deepStrictEqual(byStem.map((r) => r.id), ['main', 'main::1-gen-001']);
  const byGroup = visibleTestsetRows(TREE, state({ expanded: new Set(['main']), filter: 'main' }));
  assert.deepStrictEqual(byGroup.map((r) => r.id), ['main', 'main::1-gen-000', 'main::1-gen-001']);
  // A filter narrows what is visible; it never opens what the user closed.
  assert.deepStrictEqual(
    visibleTestsetRows(TREE, state({ filter: '001' })).map((r) => r.id),
    ['main'],
  );
});

test('the filter reads the haystack the view model built, and nothing else', () => {
  assert.ok(matchesTestsetFilter(REJECTED, 'INVALID'));
  assert.ok(matchesTestsetFilter(CASE, ' gen '.trim()));
  assert.ok(!matchesTestsetFilter(CASE, 'invalid'));
  assert.ok(matchesTestsetFilter(CASE, ''));
});

test('no manifest draws the welcome, in the words the Run view uses', () => {
  const html = renderTestsetTree({ rows: [], empty: true }, state());
  assert.ok(html.includes('No testset built for this problem.'), html);
  assert.ok(html.includes('<code>rbx build</code>'), html);
});

test('a manifest with no tests says so, and does not ask for another build', () => {
  const html = renderTestsetTree({ rows: [], empty: false }, state());
  assert.ok(html.includes('built with no testcases'), html);
  assert.ok(!html.includes('No testset built'), html);
});

test('the header states the size and the build time, and offers the panel', () => {
  const html = renderTestsetHeader(TREE);
  assert.ok(html.includes('<span class="header-summary">2 tests · 1 group</span>'), html);
  assert.ok(html.includes('<span class="header-built">built 3m ago</span>'), html);
  assert.ok(html.includes('id="open-panel"'), html);
  // No manifest, no strip: there is nothing to state.
  assert.strictEqual(renderTestsetHeader({ rows: [], empty: true }), '');
});

test('the card describes the selected testcase and nothing else', () => {
  assert.strictEqual(renderTestsetCard(TREE, state({ selected: 'main' })), '');
  assert.strictEqual(renderTestsetCard(TREE, state()), '');
  const html = renderTestsetCard(TREE, state({ selected: CASE.id }));
  assert.ok(html.includes('<div class="card-title">main/1-gen-000</div>'), html);
  assert.ok(html.includes('<span class="value-label">Input</span>'), html);
  // A generator call names no file, so it is text rather than a link that
  // promises a destination the view cannot reach.
  assert.ok(html.includes('<div class="card-origin" title="Generated by gen 1000 7">'), html);
  assert.ok(html.includes('data-action="rbx.openTestVisualization"'), html);
  assert.ok(html.includes('data-action="panel:gallery"'), html);
});

test('a declared but unbuilt channel offers a lazy button instead', () => {
  // The package was built without `--visualize`, so there is no file to open --
  // but a visualizer is declared, so it can be drawn now.
  const lazy = {
    ...CASE,
    card: {
      ...CASE.card!,
      visualization: undefined,
      answerVisualization: undefined,
      lazyVisualizers: { input: true, output: true },
    },
  };
  const html = renderTestsetCard({ ...TREE, rows: [lazy] }, state({ selected: lazy.id }));
  assert.ok(html.includes('data-action="rbx.visualizeTest"'), html);
  // The Tests view's answer channel is the *expected answer*, not a solution's
  // output, so it has its own command.
  assert.ok(html.includes('data-action="rbx.visualizeTestAnswer"'), html);
  assert.ok(!html.includes('rbx.visualizeSolutionOutput'), html);
  // Marked so the reader can tell it will do work rather than open a file.
  assert.ok(html.includes('class="card-channel lazy"'), html);
});

test('a built channel is never also offered lazily', () => {
  // Built and lazy are exclusive per channel: offering both would put two
  // buttons named `input` side by side.
  const mixed = {
    ...CASE,
    card: {
      ...CASE.card!,
      visualization: 'build/tests/main/visualization/1-gen-000.svg',
      answerVisualization: undefined,
      lazyVisualizers: { input: false, output: true },
    },
  };
  const html = renderTestsetCard(
    { ...TREE, rows: [mixed] },
    state({ selected: mixed.id }),
  );
  assert.ok(html.includes('data-action="rbx.openTestVisualization"'), html);
  assert.ok(!html.includes('data-action="rbx.visualizeTest"'), html);
  assert.ok(html.includes('data-action="rbx.visualizeTestAnswer"'), html);
});

test('a testcase with no visualizer declared gets no visualization row', () => {
  const none = {
    ...CASE,
    card: {
      ...CASE.card!,
      visualization: undefined,
      answerVisualization: undefined,
      lazyVisualizers: { input: false, output: false },
    },
  };
  const html = renderTestsetCard({ ...TREE, rows: [none] }, state({ selected: none.id }));
  assert.ok(!html.includes('card-channels'), html);
});

test('the card offers a button per visualization channel that exists', () => {
  // An unqualified `visualization` button was wrong twice over on a package
  // with both channels: it named neither, and it opened only the input one.
  const both = {
    ...CASE,
    card: {
      ...CASE.card!,
      visualization: 'build/tests/main/visualization/1-gen-000.svg',
      lazyVisualizers: { input: false, output: false },
      answerVisualization: 'build/tests/main/output_visualization/1-gen-000.svg',
    },
  };
  const html = renderTestsetCard({ ...TREE, rows: [both] }, state({ selected: both.id }));
  assert.ok(html.includes('data-action="rbx.openTestVisualization"'), html);
  assert.ok(html.includes('data-action="rbx.openTestAnswerVisualization"'), html);
  assert.ok(html.includes('>input</button>'), html);
  assert.ok(html.includes('>answer</button>'), html);
});

test('a testcase with only an answer visualization still gets its button', () => {
  const answerOnly = {
    ...CASE,
    card: {
      ...CASE.card!,
      visualization: undefined,
      answerVisualization: 'build/tests/main/output_visualization/1-gen-000.svg',
    },
  };
  const html = renderTestsetCard(
    { ...TREE, rows: [answerOnly] },
    state({ selected: answerOnly.id }),
  );
  assert.ok(html.includes('data-action="rbx.openTestAnswerVisualization"'), html);
  // And no dead button for the channel that produced nothing.
  assert.ok(!html.includes('data-action="rbx.openTestVisualization"'), html);
});

test('a rejected testcase card carries the validator and its sentence', () => {
  const html = renderTestsetCard(TREE, state({ selected: REJECTED.id }));
  assert.ok(html.includes('<div class="card-validation hue-red">'), html);
  assert.ok(html.includes('Rejected by the validator'), html);
  assert.ok(html.includes('<span class="card-validator">validator.cpp</span>'), html);
  assert.ok(html.includes('<div class="card-message">n must be at most 100</div>'), html);
  // Nothing to visualize, so no buttons at all rather than a dead one.
  assert.ok(!html.includes('card-channel'), html);
});

test('a label, a mark title and a group name are all escaped', () => {
  const nasty = row({
    id: 'a<b',
    label: '<script>x</script>',
    flags: [{ kind: 'invalid', hue: 'red', title: 'a "b" & <c>' }],
  });
  const html = renderTestsetTree(model([nasty]), state());
  assert.ok(!html.includes('<script>'), html);
  assert.ok(html.includes('title="a &quot;b&quot; &amp; &lt;c&gt;"'), html);
  assert.ok(html.includes('data-id="a&lt;b"'), html);
});

test('the responsive ladder hides a suffix of the meta line, score last', () => {
  // Pinned as a table because the *order* is the design, and it is expressed in
  // a stylesheet no unit test renders. The separator scheme in `metaCell` is
  // only correct while hiding removes a suffix: if a future breakpoint hid the
  // score while keeping the size, the surviving line would start with a `·`.
  // The compiled test sits in out-test/webview; the stylesheet it is asserting
  // about is the source one, two levels up.
  const css = readFileSync(join(__dirname, '..', '..', 'src', 'webview', 'style.css'), 'utf8');
  const widthOf = (selector: string): number => {
    const queries = [...css.matchAll(/@container \(max-width: (\d+)px\)\s*\{([\s\S]*?)\n\}/g)];
    const hit = queries.find((q) => q[2].includes(selector));
    assert.ok(hit !== undefined, `no breakpoint hides ${selector}`);
    return Number(hit[1]);
  };
  // Strictly descending: the count survives the size.
  assert.ok(
    widthOf('.span-size') > widthOf('.span-count'),
    `ladder out of order: ${widthOf('.span-size')} > ${widthOf('.span-count')}`,
  );
  // The score is never named by any of them.
  assert.ok(!css.includes('.span-score'), 'the score must outlive every breakpoint');
});
