import asyncio
from unittest import mock

import pytest
from typer.testing import CliRunner

from rbx.box.testcases import main as testcases_main
from rbx.box.testing import testing_package


def _scripted_prompt(*values):
    """Build a mock questionary prompt factory.

    Each call to the factory returns an object whose ``.ask_async()`` is an
    async function yielding the next scripted value.
    """
    values = list(values)

    def factory(*args, **kwargs):
        result = mock.MagicMock()

        async def ask_async():
            return values.pop(0)

        result.ask_async = ask_async
        return result

    return factory


def _accept_default_filenames():
    """Mock for ``_edit_filenames`` that accepts the glob-aware defaults.

    Stands in for the prompt_toolkit batch editor: it assigns the same
    sequential glob-aware default stems the real editor pre-fills, so the
    downstream write/remove behavior can be asserted without driving the TUI.
    """
    from rbx.box import promotion

    async def edit_filenames(target_group, chosen_entries, **kwargs):
        glob = target_group.testcaseGlob
        stems = promotion.default_stems(glob, len(chosen_entries))
        return list(zip(chosen_entries, stems))

    return edit_filenames


def _abort_filenames():
    """Mock for ``_edit_filenames`` that aborts (returns None), like Esc/Ctrl-C."""

    async def edit_filenames(target_group, chosen_entries, **kwargs):
        return None

    return edit_filenames


@pytest.fixture
def runner() -> CliRunner:
    # The promote command is wrapped in @syncer.sync, which calls
    # asyncio.get_event_loop() from CliRunner's synchronous context. On
    # Python 3.14 that raises unless a loop is bound to the current thread,
    # so we ensure one exists for the duration of the test.
    try:
        asyncio.get_event_loop()
    except RuntimeError:
        asyncio.set_event_loop(asyncio.new_event_loop())
    return CliRunner()


def _setup_pkg_with_script_group(
    testing_pkg: testing_package.TestingPackage,
) -> None:
    """Set up a single-line rbx generator-script group ``gen`` (test ``gen/0``)."""
    # gen-id.cpp echoes its single integer argument back as the test input.
    testing_pkg.add_generator('gens/gen.cpp', src='generators/gen-id.cpp')
    testing_pkg.add_testgroup_from_plan('gen', 'gens/gen.cpp 123\n')


def _setup_pkg_with_two_script_tests(
    testing_pkg: testing_package.TestingPackage,
) -> None:
    """Set up a two-line rbx generator-script group ``gen`` (tests ``gen/0,1``)."""
    testing_pkg.add_generator('gens/gen.cpp', src='generators/gen-id.cpp')
    testing_pkg.add_testgroup_from_plan(
        'gen',
        'gens/gen.cpp 123\ngens/gen.cpp 456\n',
    )


def _script_path(testing_pkg: testing_package.TestingPackage):
    return testing_pkg.root / 'testplan' / 'gen.txt'


def test_promote_non_interactive_happy_path(
    runner: CliRunner,
    testing_pkg: testing_package.TestingPackage,
):
    _setup_pkg_with_script_group(testing_pkg)
    (testing_pkg.root / 'tests/manual/corner').mkdir(parents=True, exist_ok=True)
    testing_pkg.add_testgroup_from_glob('corner', 'tests/manual/corner/*.in')

    result = runner.invoke(
        testcases_main.app, ['promote', 'gen/0', '--group', 'corner']
    )

    assert result.exit_code == 0, result.output
    dest = testing_pkg.root / 'tests/manual/corner/000.in'
    assert dest.is_file()
    assert dest.read_bytes() == b'123\n'
    # INPUT only -- no answer file is written.
    assert not (testing_pkg.root / 'tests/manual/corner/000.out').exists()
    assert not (testing_pkg.root / 'tests/manual/corner/000.ans').exists()
    # MOVE semantics: the source line is removed from the script.
    assert 'gens/gen.cpp 123' not in _script_path(testing_pkg).read_text()


def test_promote_move_removes_source_line(
    runner: CliRunner,
    testing_pkg: testing_package.TestingPackage,
):
    _setup_pkg_with_two_script_tests(testing_pkg)
    (testing_pkg.root / 'tests/manual/corner').mkdir(parents=True, exist_ok=True)
    testing_pkg.add_testgroup_from_glob('corner', 'tests/manual/corner/*.in')

    result = runner.invoke(
        testcases_main.app, ['promote', 'gen/0', '--group', 'corner']
    )

    assert result.exit_code == 0, result.output
    dest = testing_pkg.root / 'tests/manual/corner/000.in'
    assert dest.is_file()
    assert dest.read_bytes() == b'123\n'
    # The first line is GONE; the second remains.
    script = _script_path(testing_pkg).read_text()
    assert 'gens/gen.cpp 123' not in script
    assert 'gens/gen.cpp 456' in script


def test_promote_non_promotable_selector_errors(
    runner: CliRunner,
    testing_pkg: testing_package.TestingPackage,
):
    # A manual glob group test is not generated by a script -> not promotable.
    (testing_pkg.root / 'tests/manual/src').mkdir(parents=True, exist_ok=True)
    (testing_pkg.root / 'tests/manual/src/000.in').write_bytes(b'manual\n')
    testing_pkg.add_testgroup_from_glob('src', 'tests/manual/src/*.in')
    (testing_pkg.root / 'tests/manual/corner').mkdir(parents=True, exist_ok=True)
    testing_pkg.add_testgroup_from_glob('corner', 'tests/manual/corner/*.in')

    result = runner.invoke(
        testcases_main.app, ['promote', 'src/0', '--group', 'corner']
    )

    assert result.exit_code != 0
    assert 'cannot be promoted' in result.output
    # NO file written into the destination group.
    assert not any((testing_pkg.root / 'tests/manual/corner').glob('*.in'))
    # Source unchanged.
    assert (testing_pkg.root / 'tests/manual/src/000.in').read_bytes() == b'manual\n'


def test_promote_non_interactive_with_explicit_name(
    runner: CliRunner,
    testing_pkg: testing_package.TestingPackage,
):
    _setup_pkg_with_script_group(testing_pkg)
    (testing_pkg.root / 'tests/manual/corner').mkdir(parents=True, exist_ok=True)
    testing_pkg.add_testgroup_from_glob('corner', 'tests/manual/corner/*.in')

    result = runner.invoke(
        testcases_main.app,
        ['promote', 'gen/0', '--group', 'corner', '--name', 'special'],
    )

    assert result.exit_code == 0, result.output
    dest = testing_pkg.root / 'tests/manual/corner/special.in'
    assert dest.is_file()
    assert dest.read_bytes() == b'123\n'
    assert 'gens/gen.cpp 123' not in _script_path(testing_pkg).read_text()


def test_promote_non_interactive_nonexistent_group_errors(
    runner: CliRunner,
    testing_pkg: testing_package.TestingPackage,
):
    _setup_pkg_with_script_group(testing_pkg)

    result = runner.invoke(
        testcases_main.app, ['promote', 'gen/0', '--group', 'does-not-exist']
    )

    assert result.exit_code != 0
    assert 'does-not-exist' in result.output


def _setup_inherited_named_blocks(testing_pkg: testing_package.TestingPackage):
    """Problem-level script partitioned by @testgroup, inherited by grpa/grpb."""
    from rbx.box.schema import GeneratorScript, TestcaseGroup

    testing_pkg.add_generator('gens/gen.cpp', src='generators/gen-id.cpp')
    shared = testing_pkg.add_testplan('shared')
    shared.write_text(
        '@testgroup grpa {\n  gens/gen.cpp 123\n}\n'
        '@testgroup grpb {\n  gens/gen.cpp 456\n}\n'
    )
    testing_pkg.yml.generatorScript = GeneratorScript(path=shared)
    testing_pkg.yml.testcases = testing_pkg.yml.testcases + [
        TestcaseGroup(name='grpa'),
        TestcaseGroup(name='grpb'),
    ]
    testing_pkg.save()
    return shared


def test_promote_inherited_named_block(
    runner: CliRunner,
    testing_pkg: testing_package.TestingPackage,
):
    shared = _setup_inherited_named_blocks(testing_pkg)
    (testing_pkg.root / 'tests/manual/corner').mkdir(parents=True, exist_ok=True)
    testing_pkg.add_testgroup_from_glob('corner', 'tests/manual/corner/*.in')

    result = runner.invoke(
        testcases_main.app, ['promote', 'grpa/0', '--group', 'corner']
    )

    assert result.exit_code == 0, result.output
    dest = testing_pkg.root / 'tests/manual/corner/000.in'
    assert dest.is_file()
    assert dest.read_bytes() == b'123\n'
    text = shared.read_text()
    # The grpa line is removed; grpb's block is untouched.
    assert 'gens/gen.cpp 123' not in text
    assert 'gens/gen.cpp 456' in text


def test_promote_blocked_when_line_shared_across_groups(
    runner: CliRunner,
    testing_pkg: testing_package.TestingPackage,
):
    from rbx.box.schema import GeneratorScript, TestcaseGroup

    testing_pkg.add_generator('gens/gen.cpp', src='generators/gen-id.cpp')
    shared = testing_pkg.add_testplan('shared')
    # Untagged top-level line: it feeds BOTH inheriting groups, so removing it
    # would change grpb too -> promotion must be rejected.
    shared.write_text('gens/gen.cpp 123\n')
    testing_pkg.yml.generatorScript = GeneratorScript(path=shared)
    testing_pkg.yml.testcases = testing_pkg.yml.testcases + [
        TestcaseGroup(name='grpa'),
        TestcaseGroup(name='grpb'),
    ]
    testing_pkg.save()
    (testing_pkg.root / 'tests/manual/corner').mkdir(parents=True, exist_ok=True)
    testing_pkg.add_testgroup_from_glob('corner', 'tests/manual/corner/*.in')

    result = runner.invoke(
        testcases_main.app, ['promote', 'grpa/0', '--group', 'corner']
    )

    assert result.exit_code != 0
    assert 'cannot be promoted' in result.output
    assert 'other test group' in result.output
    # Nothing written; source untouched.
    assert not any((testing_pkg.root / 'tests/manual/corner').glob('*.in'))
    assert 'gens/gen.cpp 123' in shared.read_text()


def test_promote_interactive_existing_group(
    runner: CliRunner,
    testing_pkg: testing_package.TestingPackage,
):
    _setup_pkg_with_script_group(testing_pkg)
    (testing_pkg.root / 'tests/manual/corner').mkdir(parents=True, exist_ok=True)
    testing_pkg.add_testgroup_from_glob('corner', 'tests/manual/corner/*.in')

    # checkbox -> select one test (by its full_repr label); select -> existing
    # group; the batch filename editor accepts the default stem.
    label = 'gen/0 (gens/gen.cpp 123) [testplan/gen.txt:1]'
    with (
        mock.patch('questionary.checkbox', _scripted_prompt([label])),
        mock.patch('questionary.select', _scripted_prompt('corner')),
        mock.patch.object(
            testcases_main, '_edit_filenames', _accept_default_filenames()
        ),
    ):
        result = runner.invoke(testcases_main.app, ['promote'])

    assert result.exit_code == 0, result.output
    dest = testing_pkg.root / 'tests/manual/corner/000.in'
    assert dest.is_file()
    assert dest.read_bytes() == b'123\n'
    assert not (testing_pkg.root / 'tests/manual/corner/000.out').exists()
    assert not (testing_pkg.root / 'tests/manual/corner/000.ans').exists()
    assert 'gens/gen.cpp 123' not in _script_path(testing_pkg).read_text()


def test_promote_interactive_excludes_non_promotable_and_shows_metadata(
    runner: CliRunner,
    testing_pkg: testing_package.TestingPackage,
):
    # Mix an rbx-script group with a manual glob group; only the rbx-script test
    # is offered, and its label includes the generator-call metadata.
    _setup_pkg_with_script_group(testing_pkg)
    (testing_pkg.root / 'tests/manual/src').mkdir(parents=True, exist_ok=True)
    (testing_pkg.root / 'tests/manual/src/000.in').write_bytes(b'manual\n')
    testing_pkg.add_testgroup_from_glob('src', 'tests/manual/src/*.in')
    (testing_pkg.root / 'tests/manual/corner').mkdir(parents=True, exist_ok=True)
    testing_pkg.add_testgroup_from_glob('corner', 'tests/manual/corner/*.in')

    captured = {}

    def checkbox_factory(*args, **kwargs):
        captured['choices'] = kwargs.get('choices')
        result = mock.MagicMock()

        async def ask_async():
            # Select nothing -- we only care about the offered choices.
            return []

        result.ask_async = ask_async
        return result

    with (
        mock.patch('questionary.checkbox', checkbox_factory),
        mock.patch('questionary.select', _scripted_prompt('corner')),
        mock.patch('questionary.text', _scripted_prompt()),
    ):
        result = runner.invoke(testcases_main.app, ['promote'])

    assert result.exit_code == 0, result.output
    choices = captured['choices']
    # Only the rbx-script test is offered (the manual src/0 is excluded).
    assert choices == ['gen/0 (gens/gen.cpp 123) [testplan/gen.txt:1]']
    # Label includes the generator call and the originating script location.
    assert 'gens/gen.cpp 123' in choices[0]
    assert 'testplan/gen.txt:1' in choices[0]


def test_non_promotable_reason_dynamic_script():
    # A non-.txt (dynamic) generator script reports the dynamic-script reason.
    import pathlib

    from rbx.box.generation_schema import (
        GenerationMetadata,
        GenerationTestcaseEntry,
        GeneratorScriptEntry,
    )
    from rbx.box.schema import GeneratorCall, Testcase
    from rbx.box.testcase_schema import TestcaseEntry

    dynamic = pathlib.Path('testplan/random.py')
    entry = GenerationTestcaseEntry(
        group_entry=TestcaseEntry(group='g', index=0),
        subgroup_entry=TestcaseEntry(group='g', index=0),
        metadata=GenerationMetadata(
            copied_to=Testcase(inputPath=pathlib.Path('x.in')),
            generator_call=GeneratorCall(name='g'),
            generator_script=GeneratorScriptEntry(path=dynamic, line=1),
        ),
    )
    reason = testcases_main._non_promotable_reason(entry, {dynamic: 'rbx'}, {})  # noqa: SLF001
    assert 'dynamic generator script' in reason


def test_promote_interactive_no_promotable_tests(
    runner: CliRunner,
    testing_pkg: testing_package.TestingPackage,
):
    # Only a manual glob group exists -> nothing promotable.
    (testing_pkg.root / 'tests/manual/src').mkdir(parents=True, exist_ok=True)
    (testing_pkg.root / 'tests/manual/src/000.in').write_bytes(b'manual\n')
    testing_pkg.add_testgroup_from_glob('src', 'tests/manual/src/*.in')

    with (
        mock.patch('questionary.checkbox', _scripted_prompt()),
        mock.patch('questionary.select', _scripted_prompt()),
        mock.patch('questionary.text', _scripted_prompt()),
    ):
        result = runner.invoke(testcases_main.app, ['promote'])

    assert result.exit_code == 0, result.output
    assert 'No promotable tests found' in result.output


def test_promote_interactive_create_new_group(
    runner: CliRunner,
    testing_pkg: testing_package.TestingPackage,
):
    _setup_pkg_with_script_group(testing_pkg)

    glob = 'tests/manual/fresh/*.in'
    label = 'gen/0 (gens/gen.cpp 123) [testplan/gen.txt:1]'
    # checkbox -> select test; select -> create new; text -> name, then glob (the
    # group-creation prompts); the batch filename editor accepts the default.
    with (
        mock.patch('questionary.checkbox', _scripted_prompt([label])),
        mock.patch('questionary.select', _scripted_prompt('(create new manual group)')),
        mock.patch('questionary.text', _scripted_prompt('fresh', glob)),
        mock.patch.object(
            testcases_main, '_edit_filenames', _accept_default_filenames()
        ),
    ):
        result = runner.invoke(testcases_main.app, ['promote'])

    assert result.exit_code == 0, result.output
    folder = testing_pkg.root / 'tests/manual/fresh'
    assert folder.is_dir()
    dest = folder / '000.in'
    assert dest.is_file()
    assert dest.read_bytes() == b'123\n'
    assert 'gens/gen.cpp 123' not in _script_path(testing_pkg).read_text()

    from rbx.box import package

    package_obj = package.find_problem_package_or_die()
    groups = {g.name: g for g in package_obj.testcases}
    assert 'fresh' in groups
    assert groups['fresh'].testcaseGlob == glob


def test_promote_interactive_two_defaults_sequential(
    runner: CliRunner,
    testing_pkg: testing_package.TestingPackage,
):
    _setup_pkg_with_two_script_tests(testing_pkg)
    (testing_pkg.root / 'tests/manual/corner').mkdir(parents=True, exist_ok=True)
    testing_pkg.add_testgroup_from_glob('corner', 'tests/manual/corner/*.in')

    # checkbox -> select both tests; select -> existing group; the batch editor
    # accepts the defaults. The glob-aware counter must produce 000 then 001,
    # writing two distinct files.
    labels = [
        'gen/0 (gens/gen.cpp 123) [testplan/gen.txt:1]',
        'gen/1 (gens/gen.cpp 456) [testplan/gen.txt:2]',
    ]
    with (
        mock.patch('questionary.checkbox', _scripted_prompt(labels)),
        mock.patch('questionary.select', _scripted_prompt('corner')),
        mock.patch.object(
            testcases_main, '_edit_filenames', _accept_default_filenames()
        ),
    ):
        result = runner.invoke(testcases_main.app, ['promote'])

    assert result.exit_code == 0, result.output
    folder = testing_pkg.root / 'tests/manual/corner'
    assert (folder / '000.in').is_file()
    assert (folder / '001.in').is_file()
    written = {(folder / '000.in').read_bytes(), (folder / '001.in').read_bytes()}
    assert written == {b'123\n', b'456\n'}
    # Both source lines were removed.
    script = _script_path(testing_pkg).read_text()
    assert 'gens/gen.cpp 123' not in script
    assert 'gens/gen.cpp 456' not in script


def test_promote_interactive_prefixed_glob_matches(
    runner: CliRunner,
    testing_pkg: testing_package.TestingPackage,
):
    # Regression: a prefixed glob (manual-*.in) must receive a file matching the
    # glob (manual-000.in), not 000.in, so it is picked up at build time.
    import fnmatch

    _setup_pkg_with_script_group(testing_pkg)
    (testing_pkg.root / 'manual_tests').mkdir(parents=True, exist_ok=True)
    testing_pkg.add_testgroup_from_glob('manual', 'manual_tests/manual-*.in')

    label = 'gen/0 (gens/gen.cpp 123) [testplan/gen.txt:1]'
    with (
        mock.patch('questionary.checkbox', _scripted_prompt([label])),
        mock.patch('questionary.select', _scripted_prompt('manual')),
        mock.patch.object(
            testcases_main, '_edit_filenames', _accept_default_filenames()
        ),
    ):
        result = runner.invoke(testcases_main.app, ['promote'])

    assert result.exit_code == 0, result.output
    dest = testing_pkg.root / 'manual_tests/manual-000.in'
    assert dest.is_file()
    assert dest.read_bytes() == b'123\n'
    # The written path matches the group's own glob.
    assert fnmatch.fnmatch('manual_tests/manual-000.in', 'manual_tests/manual-*.in')
    # The plain 000.in (the buggy destination) is NOT written.
    assert not (testing_pkg.root / 'manual_tests/000.in').exists()
    assert 'gens/gen.cpp 123' not in _script_path(testing_pkg).read_text()


def test_promote_interactive_abort_editor_writes_nothing(
    runner: CliRunner,
    testing_pkg: testing_package.TestingPackage,
):
    # Aborting the batch filename editor (Esc/Ctrl-C -> None) must write nothing
    # and leave the source script untouched.
    _setup_pkg_with_script_group(testing_pkg)
    (testing_pkg.root / 'tests/manual/corner').mkdir(parents=True, exist_ok=True)
    testing_pkg.add_testgroup_from_glob('corner', 'tests/manual/corner/*.in')

    label = 'gen/0 (gens/gen.cpp 123) [testplan/gen.txt:1]'
    with (
        mock.patch('questionary.checkbox', _scripted_prompt([label])),
        mock.patch('questionary.select', _scripted_prompt('corner')),
        mock.patch.object(testcases_main, '_edit_filenames', _abort_filenames()),
    ):
        result = runner.invoke(testcases_main.app, ['promote'])

    assert result.exit_code == 0, result.output
    folder = testing_pkg.root / 'tests/manual/corner'
    assert not any(folder.glob('*.in'))
    # Source untouched.
    assert 'gens/gen.cpp 123' in _script_path(testing_pkg).read_text()


def test_promote_non_interactive_name_ignored_for_multiple(
    runner: CliRunner,
    testing_pkg: testing_package.TestingPackage,
):
    _setup_pkg_with_two_script_tests(testing_pkg)
    (testing_pkg.root / 'tests/manual/corner').mkdir(parents=True, exist_ok=True)
    testing_pkg.add_testgroup_from_glob('corner', 'tests/manual/corner/*.in')

    result = runner.invoke(
        testcases_main.app,
        ['promote', 'gen/0', 'gen/1', '--group', 'corner', '--name', 'foo'],
    )

    assert result.exit_code == 0, result.output
    assert '--name is ignored' in result.output
    folder = testing_pkg.root / 'tests/manual/corner'
    # --name was NOT applied: auto-counter names are used instead.
    assert not (folder / 'foo.in').exists()
    assert (folder / '000.in').is_file()
    assert (folder / '001.in').is_file()
    written = {(folder / '000.in').read_bytes(), (folder / '001.in').read_bytes()}
    assert written == {b'123\n', b'456\n'}
    script = _script_path(testing_pkg).read_text()
    assert 'gens/gen.cpp 123' not in script
    assert 'gens/gen.cpp 456' not in script


def test_promote_interactive_skip_writes_nothing(
    runner: CliRunner,
    testing_pkg: testing_package.TestingPackage,
):
    _setup_pkg_with_script_group(testing_pkg)
    (testing_pkg.root / 'tests/manual/corner').mkdir(parents=True, exist_ok=True)
    testing_pkg.add_testgroup_from_glob('corner', 'tests/manual/corner/*.in')

    # checkbox -> select a test; select -> skip the group picker. Nothing should
    # be written, no group added, and the source line must be untouched.
    label = 'gen/0 (gens/gen.cpp 123) [testplan/gen.txt:1]'
    with (
        mock.patch('questionary.checkbox', _scripted_prompt([label])),
        mock.patch('questionary.select', _scripted_prompt('(skip)')),
        mock.patch('questionary.text', _scripted_prompt()),
    ):
        result = runner.invoke(testcases_main.app, ['promote'])

    assert result.exit_code == 0, result.output
    folder = testing_pkg.root / 'tests/manual/corner'
    assert not any(folder.glob('*.in'))
    # Source untouched.
    assert 'gens/gen.cpp 123' in _script_path(testing_pkg).read_text()


# --- batch filename editor: state + prompt_toolkit smoke -------------------


def _make_entries(*reprs):
    """Build minimal GenerationTestcaseEntry objects with the given generator."""
    import pathlib

    from rbx.box.generation_schema import (
        GenerationMetadata,
        GenerationTestcaseEntry,
        GeneratorScriptEntry,
    )
    from rbx.box.schema import GeneratorCall, Testcase
    from rbx.box.testcase_schema import TestcaseEntry

    entries = []
    for i, rep in enumerate(reprs):
        md = GenerationMetadata(
            copied_to=Testcase(inputPath=pathlib.Path(f'{i}.in')),
            generator_call=GeneratorCall(name=rep),
            generator_script=GeneratorScriptEntry(
                path=pathlib.Path('plan.txt'), line=i
            ),
        )
        entries.append(
            GenerationTestcaseEntry(
                group_entry=TestcaseEntry(group='gen', index=i),
                subgroup_entry=TestcaseEntry(group='gen', index=i),
                metadata=md,
            )
        )
    return entries


def test_filename_editor_state_renders_preview_around_stem():
    entries = _make_entries('a', 'b')
    state = testcases_main._FilenameEditorState(  # noqa: SLF001
        entries, 'manual_tests/manual-*.in', ['000', '001']
    )
    text = ''.join(t for _, t in state.render_fragments())
    # The fixed glob prefix/suffix frame the editable stem -> full path preview.
    assert 'manual_tests/manual-000.in' in text
    assert 'manual_tests/manual-001.in' in text


def test_filename_editor_state_move_wraps_and_edits_focused():
    entries = _make_entries('a', 'b')
    state = testcases_main._FilenameEditorState(  # noqa: SLF001
        entries, 'tests/*.in', ['000', '001']
    )
    assert state.cursor == 0
    state.move(-1)  # wraps to last
    assert state.cursor == 1
    state.type_char('x')
    assert state.stems[1] == '001x'
    state.backspace()
    assert state.stems[1] == '001'


def test_filename_editor_state_error_on_duplicate():
    entries = _make_entries('a', 'b')
    state = testcases_main._FilenameEditorState(  # noqa: SLF001
        entries, 'tests/*.in', ['000', '000']
    )
    assert state.error() is not None


async def test_edit_filenames_type_and_submit(cleandir):
    from prompt_toolkit.input.defaults import create_pipe_input
    from prompt_toolkit.output import DummyOutput

    from rbx.box.schema import TestcaseGroup

    entries = _make_entries('a', 'b')
    group = TestcaseGroup(name='manual', testcaseGlob='manual_tests/manual-*.in')

    with create_pipe_input() as inp:
        # Append 'z' to the first stem (000 -> 000z), then submit with enter.
        inp.send_text('z')
        inp.send_text('\r')
        result = await testcases_main._edit_filenames(  # noqa: SLF001
            group, entries, input=inp, output=DummyOutput()
        )

    assert result is not None
    assert [stem for _, stem in result] == ['000z', '001']
    assert [e for e, _ in result] == entries


async def test_edit_filenames_ignores_typed_whitespace(cleandir):
    from prompt_toolkit.input.defaults import create_pipe_input
    from prompt_toolkit.output import DummyOutput

    from rbx.box.schema import TestcaseGroup

    entries = _make_entries('a')
    group = TestcaseGroup(name='manual', testcaseGlob='manual_tests/manual-*.in')

    with create_pipe_input() as inp:
        # A space must be ignored (no awkward 'manual-000 .in'); the 'z' still
        # lands, so the stem becomes '000z' rather than '000 z'.
        inp.send_text(' ')
        inp.send_text('z')
        inp.send_text('\r')
        result = await testcases_main._edit_filenames(  # noqa: SLF001
            group, entries, input=inp, output=DummyOutput()
        )

    assert result is not None
    assert [stem for _, stem in result] == ['000z']


async def test_edit_filenames_escape_aborts(cleandir):
    from prompt_toolkit.input.defaults import create_pipe_input
    from prompt_toolkit.output import DummyOutput

    from rbx.box.schema import TestcaseGroup

    entries = _make_entries('a')
    group = TestcaseGroup(name='manual', testcaseGlob='manual_tests/manual-*.in')

    with create_pipe_input() as inp:
        inp.send_text('\x1b')  # Esc -> abort
        result = await testcases_main._edit_filenames(  # noqa: SLF001
            group, entries, input=inp, output=DummyOutput()
        )

    assert result is None


async def test_edit_filenames_blocks_submit_while_invalid(cleandir):
    from prompt_toolkit.input.defaults import create_pipe_input
    from prompt_toolkit.output import DummyOutput

    from rbx.box.schema import TestcaseGroup

    entries = _make_entries('a', 'b')
    group = TestcaseGroup(name='manual', testcaseGlob='manual_tests/manual-*.in')

    with create_pipe_input() as inp:
        # Clear the first stem (000 -> '') making the batch invalid (empty name).
        for _ in range(3):
            inp.send_text('\x7f')  # backspace x3
        inp.send_text('\r')  # enter is blocked while invalid
        # Recover by typing a valid distinct stem, then submit.
        inp.send_text('9')
        inp.send_text('\r')
        result = await testcases_main._edit_filenames(  # noqa: SLF001
            group, entries, input=inp, output=DummyOutput()
        )

    assert result is not None
    assert [stem for _, stem in result] == ['9', '001']
