import asyncio
from unittest import mock

import pytest
from typer.testing import CliRunner

from rbx.box.testcases import main as testcases_main
from rbx.box.testing import testing_package


def _scripted_prompt(*values):
    """Build a mock questionary prompt factory.

    Each call to the factory returns an object whose ``.ask_async()`` is an
    async function yielding the next scripted value.
    """
    values = list(values)

    def factory(*args, **kwargs):
        result = mock.MagicMock()

        async def ask_async():
            return values.pop(0)

        result.ask_async = ask_async
        return result

    return factory


@pytest.fixture
def runner() -> CliRunner:
    # The promote command is wrapped in @syncer.sync, which calls
    # asyncio.get_event_loop() from CliRunner's synchronous context. On
    # Python 3.14 that raises unless a loop is bound to the current thread,
    # so we ensure one exists for the duration of the test.
    try:
        asyncio.get_event_loop()
    except RuntimeError:
        asyncio.set_event_loop(asyncio.new_event_loop())
    return CliRunner()


def _setup_pkg_with_script_group(
    testing_pkg: testing_package.TestingPackage,
) -> None:
    """Set up a single-line rbx generator-script group ``gen`` (test ``gen/0``)."""
    # gen-id.cpp echoes its single integer argument back as the test input.
    testing_pkg.add_generator('gens/gen.cpp', src='generators/gen-id.cpp')
    testing_pkg.add_testgroup_from_plan('gen', 'gens/gen.cpp 123\n')


def _setup_pkg_with_two_script_tests(
    testing_pkg: testing_package.TestingPackage,
) -> None:
    """Set up a two-line rbx generator-script group ``gen`` (tests ``gen/0,1``)."""
    testing_pkg.add_generator('gens/gen.cpp', src='generators/gen-id.cpp')
    testing_pkg.add_testgroup_from_plan(
        'gen',
        'gens/gen.cpp 123\ngens/gen.cpp 456\n',
    )


def _script_path(testing_pkg: testing_package.TestingPackage):
    return testing_pkg.root / 'testplan' / 'gen.txt'


def test_promote_non_interactive_happy_path(
    runner: CliRunner,
    testing_pkg: testing_package.TestingPackage,
):
    _setup_pkg_with_script_group(testing_pkg)
    (testing_pkg.root / 'tests/manual/corner').mkdir(parents=True, exist_ok=True)
    testing_pkg.add_testgroup_from_glob('corner', 'tests/manual/corner/*.in')

    result = runner.invoke(
        testcases_main.app, ['promote', 'gen/0', '--group', 'corner']
    )

    assert result.exit_code == 0, result.output
    dest = testing_pkg.root / 'tests/manual/corner/000.in'
    assert dest.is_file()
    assert dest.read_bytes() == b'123\n'
    # INPUT only -- no answer file is written.
    assert not (testing_pkg.root / 'tests/manual/corner/000.out').exists()
    assert not (testing_pkg.root / 'tests/manual/corner/000.ans').exists()
    # MOVE semantics: the source line is removed from the script.
    assert 'gens/gen.cpp 123' not in _script_path(testing_pkg).read_text()


def test_promote_move_removes_source_line(
    runner: CliRunner,
    testing_pkg: testing_package.TestingPackage,
):
    _setup_pkg_with_two_script_tests(testing_pkg)
    (testing_pkg.root / 'tests/manual/corner').mkdir(parents=True, exist_ok=True)
    testing_pkg.add_testgroup_from_glob('corner', 'tests/manual/corner/*.in')

    result = runner.invoke(
        testcases_main.app, ['promote', 'gen/0', '--group', 'corner']
    )

    assert result.exit_code == 0, result.output
    dest = testing_pkg.root / 'tests/manual/corner/000.in'
    assert dest.is_file()
    assert dest.read_bytes() == b'123\n'
    # The first line is GONE; the second remains.
    script = _script_path(testing_pkg).read_text()
    assert 'gens/gen.cpp 123' not in script
    assert 'gens/gen.cpp 456' in script


def test_promote_non_promotable_selector_errors(
    runner: CliRunner,
    testing_pkg: testing_package.TestingPackage,
):
    # A manual glob group test is not generated by a script -> not promotable.
    (testing_pkg.root / 'tests/manual/src').mkdir(parents=True, exist_ok=True)
    (testing_pkg.root / 'tests/manual/src/000.in').write_bytes(b'manual\n')
    testing_pkg.add_testgroup_from_glob('src', 'tests/manual/src/*.in')
    (testing_pkg.root / 'tests/manual/corner').mkdir(parents=True, exist_ok=True)
    testing_pkg.add_testgroup_from_glob('corner', 'tests/manual/corner/*.in')

    result = runner.invoke(
        testcases_main.app, ['promote', 'src/0', '--group', 'corner']
    )

    assert result.exit_code != 0
    assert 'cannot be promoted' in result.output
    # NO file written into the destination group.
    assert not any((testing_pkg.root / 'tests/manual/corner').glob('*.in'))
    # Source unchanged.
    assert (testing_pkg.root / 'tests/manual/src/000.in').read_bytes() == b'manual\n'


def test_promote_non_interactive_with_explicit_name(
    runner: CliRunner,
    testing_pkg: testing_package.TestingPackage,
):
    _setup_pkg_with_script_group(testing_pkg)
    (testing_pkg.root / 'tests/manual/corner').mkdir(parents=True, exist_ok=True)
    testing_pkg.add_testgroup_from_glob('corner', 'tests/manual/corner/*.in')

    result = runner.invoke(
        testcases_main.app,
        ['promote', 'gen/0', '--group', 'corner', '--name', 'special'],
    )

    assert result.exit_code == 0, result.output
    dest = testing_pkg.root / 'tests/manual/corner/special.in'
    assert dest.is_file()
    assert dest.read_bytes() == b'123\n'
    assert 'gens/gen.cpp 123' not in _script_path(testing_pkg).read_text()


def test_promote_non_interactive_nonexistent_group_errors(
    runner: CliRunner,
    testing_pkg: testing_package.TestingPackage,
):
    _setup_pkg_with_script_group(testing_pkg)

    result = runner.invoke(
        testcases_main.app, ['promote', 'gen/0', '--group', 'does-not-exist']
    )

    assert result.exit_code != 0
    assert 'does-not-exist' in result.output


def test_promote_interactive_existing_group(
    runner: CliRunner,
    testing_pkg: testing_package.TestingPackage,
):
    _setup_pkg_with_script_group(testing_pkg)
    (testing_pkg.root / 'tests/manual/corner').mkdir(parents=True, exist_ok=True)
    testing_pkg.add_testgroup_from_glob('corner', 'tests/manual/corner/*.in')

    # checkbox -> select one test (by its full_repr label); select -> existing
    # group; text -> accept default.
    label = 'gen/0 (gens/gen.cpp 123)'
    with (
        mock.patch('questionary.checkbox', _scripted_prompt([label])),
        mock.patch('questionary.select', _scripted_prompt('corner')),
        mock.patch('questionary.text', _scripted_prompt('')),
    ):
        result = runner.invoke(testcases_main.app, ['promote'])

    assert result.exit_code == 0, result.output
    dest = testing_pkg.root / 'tests/manual/corner/000.in'
    assert dest.is_file()
    assert dest.read_bytes() == b'123\n'
    assert not (testing_pkg.root / 'tests/manual/corner/000.out').exists()
    assert not (testing_pkg.root / 'tests/manual/corner/000.ans').exists()
    assert 'gens/gen.cpp 123' not in _script_path(testing_pkg).read_text()


def test_promote_interactive_excludes_non_promotable_and_shows_metadata(
    runner: CliRunner,
    testing_pkg: testing_package.TestingPackage,
):
    # Mix an rbx-script group with a manual glob group; only the rbx-script test
    # is offered, and its label includes the generator-call metadata.
    _setup_pkg_with_script_group(testing_pkg)
    (testing_pkg.root / 'tests/manual/src').mkdir(parents=True, exist_ok=True)
    (testing_pkg.root / 'tests/manual/src/000.in').write_bytes(b'manual\n')
    testing_pkg.add_testgroup_from_glob('src', 'tests/manual/src/*.in')
    (testing_pkg.root / 'tests/manual/corner').mkdir(parents=True, exist_ok=True)
    testing_pkg.add_testgroup_from_glob('corner', 'tests/manual/corner/*.in')

    captured = {}

    def checkbox_factory(*args, **kwargs):
        captured['choices'] = kwargs.get('choices')
        result = mock.MagicMock()

        async def ask_async():
            # Select nothing -- we only care about the offered choices.
            return []

        result.ask_async = ask_async
        return result

    with (
        mock.patch('questionary.checkbox', checkbox_factory),
        mock.patch('questionary.select', _scripted_prompt('corner')),
        mock.patch('questionary.text', _scripted_prompt()),
    ):
        result = runner.invoke(testcases_main.app, ['promote'])

    assert result.exit_code == 0, result.output
    choices = captured['choices']
    # Only the rbx-script test is offered (the manual src/0 is excluded).
    assert choices == ['gen/0 (gens/gen.cpp 123)']
    # Label includes the metadata (generator call text from full_repr()).
    assert 'gens/gen.cpp 123' in choices[0]


def test_promote_interactive_no_promotable_tests(
    runner: CliRunner,
    testing_pkg: testing_package.TestingPackage,
):
    # Only a manual glob group exists -> nothing promotable.
    (testing_pkg.root / 'tests/manual/src').mkdir(parents=True, exist_ok=True)
    (testing_pkg.root / 'tests/manual/src/000.in').write_bytes(b'manual\n')
    testing_pkg.add_testgroup_from_glob('src', 'tests/manual/src/*.in')

    with (
        mock.patch('questionary.checkbox', _scripted_prompt()),
        mock.patch('questionary.select', _scripted_prompt()),
        mock.patch('questionary.text', _scripted_prompt()),
    ):
        result = runner.invoke(testcases_main.app, ['promote'])

    assert result.exit_code == 0, result.output
    assert 'No promotable tests found' in result.output


def test_promote_interactive_create_new_group(
    runner: CliRunner,
    testing_pkg: testing_package.TestingPackage,
):
    _setup_pkg_with_script_group(testing_pkg)

    glob = 'tests/manual/fresh/*.in'
    label = 'gen/0 (gens/gen.cpp 123)'
    # checkbox -> select test; select -> create new; text -> name, then glob,
    # then filename stem (accept default).
    with (
        mock.patch('questionary.checkbox', _scripted_prompt([label])),
        mock.patch('questionary.select', _scripted_prompt('(create new manual group)')),
        mock.patch('questionary.text', _scripted_prompt('fresh', glob, '')),
    ):
        result = runner.invoke(testcases_main.app, ['promote'])

    assert result.exit_code == 0, result.output
    folder = testing_pkg.root / 'tests/manual/fresh'
    assert folder.is_dir()
    dest = folder / '000.in'
    assert dest.is_file()
    assert dest.read_bytes() == b'123\n'
    assert 'gens/gen.cpp 123' not in _script_path(testing_pkg).read_text()

    from rbx.box import package

    package_obj = package.find_problem_package_or_die()
    groups = {g.name: g for g in package_obj.testcases}
    assert 'fresh' in groups
    assert groups['fresh'].testcaseGlob == glob


def test_promote_interactive_two_defaults_sequential(
    runner: CliRunner,
    testing_pkg: testing_package.TestingPackage,
):
    _setup_pkg_with_two_script_tests(testing_pkg)
    (testing_pkg.root / 'tests/manual/corner').mkdir(parents=True, exist_ok=True)
    testing_pkg.add_testgroup_from_glob('corner', 'tests/manual/corner/*.in')

    # checkbox -> select both tests; select -> existing group; text -> accept
    # default for both (empty string each). The simulated counter must produce
    # 000 then 001, writing two distinct files.
    labels = ['gen/0 (gens/gen.cpp 123)', 'gen/1 (gens/gen.cpp 456)']
    with (
        mock.patch('questionary.checkbox', _scripted_prompt(labels)),
        mock.patch('questionary.select', _scripted_prompt('corner')),
        mock.patch('questionary.text', _scripted_prompt('', '')),
    ):
        result = runner.invoke(testcases_main.app, ['promote'])

    assert result.exit_code == 0, result.output
    folder = testing_pkg.root / 'tests/manual/corner'
    assert (folder / '000.in').is_file()
    assert (folder / '001.in').is_file()
    written = {(folder / '000.in').read_bytes(), (folder / '001.in').read_bytes()}
    assert written == {b'123\n', b'456\n'}
    # Both source lines were removed.
    script = _script_path(testing_pkg).read_text()
    assert 'gens/gen.cpp 123' not in script
    assert 'gens/gen.cpp 456' not in script


def test_promote_non_interactive_name_ignored_for_multiple(
    runner: CliRunner,
    testing_pkg: testing_package.TestingPackage,
):
    _setup_pkg_with_two_script_tests(testing_pkg)
    (testing_pkg.root / 'tests/manual/corner').mkdir(parents=True, exist_ok=True)
    testing_pkg.add_testgroup_from_glob('corner', 'tests/manual/corner/*.in')

    result = runner.invoke(
        testcases_main.app,
        ['promote', 'gen/0', 'gen/1', '--group', 'corner', '--name', 'foo'],
    )

    assert result.exit_code == 0, result.output
    assert '--name is ignored' in result.output
    folder = testing_pkg.root / 'tests/manual/corner'
    # --name was NOT applied: auto-counter names are used instead.
    assert not (folder / 'foo.in').exists()
    assert (folder / '000.in').is_file()
    assert (folder / '001.in').is_file()
    written = {(folder / '000.in').read_bytes(), (folder / '001.in').read_bytes()}
    assert written == {b'123\n', b'456\n'}
    script = _script_path(testing_pkg).read_text()
    assert 'gens/gen.cpp 123' not in script
    assert 'gens/gen.cpp 456' not in script


def test_promote_interactive_skip_writes_nothing(
    runner: CliRunner,
    testing_pkg: testing_package.TestingPackage,
):
    _setup_pkg_with_script_group(testing_pkg)
    (testing_pkg.root / 'tests/manual/corner').mkdir(parents=True, exist_ok=True)
    testing_pkg.add_testgroup_from_glob('corner', 'tests/manual/corner/*.in')

    # checkbox -> select a test; select -> skip the group picker. Nothing should
    # be written, no group added, and the source line must be untouched.
    label = 'gen/0 (gens/gen.cpp 123)'
    with (
        mock.patch('questionary.checkbox', _scripted_prompt([label])),
        mock.patch('questionary.select', _scripted_prompt('(skip)')),
        mock.patch('questionary.text', _scripted_prompt()),
    ):
        result = runner.invoke(testcases_main.app, ['promote'])

    assert result.exit_code == 0, result.output
    folder = testing_pkg.root / 'tests/manual/corner'
    assert not any(folder.glob('*.in'))
    # Source untouched.
    assert 'gens/gen.cpp 123' in _script_path(testing_pkg).read_text()
