"""What `rbx tool domjudge configure` would change, decided before anything is sent.

Everything in this module is pure: it takes the environment and the server's
current state and returns a `Plan`. `configure.py` is what talks to DOMjudge.
The split is not tidiness -- the plan is also what gets printed, so the summary
the setter reads is the same object that is applied, rather than a second
description of it that can drift.

Three DOMjudge facts shape all of it, and each is verified against a live 9.0.0:

- `POST /languages` is a whole-instance declaration: it disables submission for
  every language *not* in the payload. So the payload always carries the
  server's currently-enabled languages back, untouched.
- It matches on `externalid`, not on the id shown in the admin UI, and silently
  ignores an id that matches nothing. So the plan is verified by re-reading the
  language list afterwards rather than by trusting the 200.
- `GET /languages` only lists languages that are enabled. A disabled language
  cannot be discovered, only named -- hence `extensions.domjudge.languages`.
"""

import dataclasses
import io
import re
import zipfile
from typing import Any, Dict, List, Optional, Tuple

from rbx.box.environment import Environment, EnvironmentLanguage
from rbx.box.tooling.domjudge.extension import (
    DomjudgeExtension,
    DomjudgeLanguageExtension,
)

# The compile wrapper DOMjudge invokes. `compile.sh` calls it as
# `<script> <dest> <memlimit> <source>...`, and the two leading arguments are
# shifted off so `"$@"` is exactly the source files.
_COMPILE_SCRIPT_TEMPLATE = """#!/bin/sh
# Generated by `rbx tool domjudge configure` from env.rbx.yml (rbx language: {name}).
#
# DOMjudge calls this as: <script> <destination> <memory limit in kB> <source>...
DEST="$1" ; shift
MEMLIMIT="$1" ; shift

{command}
exit $?
"""

# Every DOMjudge compile executable is a zip of two scripts. `build` compiles the
# compile script itself, which for a shell script is nothing at all; the stock
# executables ship exactly this stub.
_BUILD_SCRIPT = """#!/bin/sh
# nothing to compile
"""

# A fixed timestamp so the same environment always produces the same zip.
_ZIP_TIMESTAMP = (1980, 1, 1, 0, 0, 0)

_PLACEHOLDER_RE = re.compile(r'\{[a-zA-Z_][a-zA-Z0-9_]*\}')

# The `env.rbx.yml` limit -> DOMjudge configuration key mapping, with the unit
# conversion each one needs. DOMjudge keeps `memory_limit` in kB; the other
# three are already in the units rbx spells them in.
_CONFIG_KEYS: List[Tuple[str, str, int]] = [
    ('memoryLimit', 'memory_limit', 1024),
    ('outputLimit', 'output_limit', 1),
    ('processLimit', 'process_limit', 1),
    ('sourceSizeLimit', 'sourcesize_limit', 1),
]


@dataclasses.dataclass(frozen=True)
class CompileScript:
    """The compile executable rbx would upload for one language."""

    command: str
    script: str

    def zip_bytes(self) -> bytes:
        """The `{run, build}` zip `POST /languages/{id}/executable` expects.

        The executable bit has to travel in the zip's unix external attributes:
        DOMjudge reads them back to decide whether the entry is runnable, and a
        compile script that is not executable fails every submission.
        """
        buffer = io.BytesIO()
        with zipfile.ZipFile(buffer, 'w', zipfile.ZIP_DEFLATED) as archive:
            for filename, content in (
                ('run', self.script),
                ('build', _BUILD_SCRIPT),
            ):
                info = zipfile.ZipInfo(filename, date_time=_ZIP_TIMESTAMP)
                info.external_attr = 0o100755 << 16
                info.compress_type = zipfile.ZIP_DEFLATED
                archive.writestr(info, content)
        return buffer.getvalue()


@dataclasses.dataclass(frozen=True)
class LanguagePlan:
    """One rbx language, and the DOMjudge language it lands on."""

    name: str
    language_id: str
    # Whether `extensions.domjudge.languages` named this id, as opposed to rbx
    # having matched it by file extension against the server's language list.
    explicit: bool
    # Whether the server currently lists this language at all. False means it is
    # disabled there, which is also why rbx knows nothing else about it.
    known: bool
    added_extensions: List[str]
    all_extensions: List[str]
    time_factor: Optional[float]
    compile_script: Optional[CompileScript]
    # Why no compile script is being pushed, when none is.
    compile_skipped: Optional[str]

    def payload(self) -> Dict[str, Any]:
        """This language's entry in the `POST /languages` document."""
        entry: Dict[str, Any] = {'id': self.language_id, 'allow_submit': True}
        if self.known:
            entry['extensions'] = self.all_extensions
        if self.time_factor is not None:
            entry['time_factor'] = self.time_factor
        return entry


@dataclasses.dataclass(frozen=True)
class ConfigChange:
    key: str
    current: Any
    desired: Any


@dataclasses.dataclass(frozen=True)
class Plan:
    languages: List[LanguagePlan]
    # Languages the server has enabled that rbx does not manage. They are carried
    # back into the payload verbatim; without them the POST would disable them.
    preserved: List[str]
    # rbx languages that matched no DOMjudge language.
    unmatched: List[str]
    config: List[ConfigChange]

    @property
    def managed_ids(self) -> List[str]:
        return [language.language_id for language in self.languages]

    def languages_payload(self) -> List[Dict[str, Any]]:
        """The whole `POST /languages` document, managed and preserved alike."""
        entries = [language.payload() for language in self.languages]
        entries.extend(
            {'id': language_id, 'allow_submit': True} for language_id in self.preserved
        )
        return entries

    def is_empty(self) -> bool:
        return not self.languages and not self.config


def _language_extension(
    language: EnvironmentLanguage,
) -> DomjudgeLanguageExtension:
    return language.get_extension_or_default('domjudge', DomjudgeLanguageExtension)


def _environment_extension(environment: Environment) -> DomjudgeExtension:
    if environment.extensions is None:
        return DomjudgeExtension()
    return getattr(environment.extensions, 'domjudge', None) or DomjudgeExtension()


def language_extensions(language: EnvironmentLanguage) -> List[str]:
    """The file extensions this rbx language owns, DOMjudge-shaped.

    Deduplicated and lowercased, primary first, because that is the order the
    setter wrote them in and DOMjudge shows the list as-is.
    """
    result: List[str] = []
    for extension in [language.extension, *language.extraExtensions]:
        normalized = extension.lstrip('.').lower()
        if normalized and normalized not in result:
            result.append(normalized)
    return result


def match_by_extension(
    server_languages: List[Dict[str, Any]], extensions: List[str]
) -> Optional[str]:
    """The enabled DOMjudge language that already accepts one of `extensions`.

    Matched on extension rather than on name for the same reason
    `runners/domjudge/staging.py` does it: the ids are an instance's own
    business, while the extension is a property of the files rbx produces.
    """
    for server_language in server_languages:
        known = {
            str(item).lstrip('.').lower()
            for item in server_language.get('extensions') or []
        }
        if known & set(extensions):
            language_id = server_language.get('id')
            if language_id is not None:
                return str(language_id)
    return None


def runs_the_binary_directly(
    environment: Environment, language: EnvironmentLanguage
) -> bool:
    """Whether rbx executes this language's build product and nothing else.

    The question DOMjudge really asks of a compile script is not "does it
    compile" but "is what you left at `$DEST` the thing I should exec". Its run
    wrapper runs that path directly, and unlike the compile script it is a global
    executable with **no write endpoint at all** -- `GET /executables/{id}` is
    the only route to it. So a language whose run command wraps the artifact in
    an interpreter (`java -cp {executable} MainKt`) cannot have its compile step
    replaced in isolation: DOMjudge's own script for it emits a shell wrapper as
    `$DEST` precisely because that is the only place left to put the `java`
    invocation.
    """
    command = language.execution.command
    if command is None and environment.defaultExecution is not None:
        command = environment.defaultExecution.command
    if command is None:
        return False
    stripped = command.strip()
    if stripped.startswith('./'):
        stripped = stripped[2:]
    return stripped == '{executable}'


def build_compile_script(
    environment: Environment,
    language: EnvironmentLanguage,
    extension: DomjudgeLanguageExtension,
) -> Tuple[Optional[CompileScript], Optional[str]]:
    """The compile wrapper for `language`, or the reason there is none.

    The translation is deliberately narrow, and every refusal below is a case
    that would otherwise be *accepted* by DOMjudge and then fail every
    submission: the endpoint answers 204 to any zip, and a wrapper that leaves
    the wrong kind of artifact at `$DEST` only shows up as a judging error.
    """
    if not extension.compile:
        return None, 'compile is false in extensions.domjudge'

    if not runs_the_binary_directly(environment, language):
        return (
            None,
            'rbx does not run this language by executing its build product, so '
            "DOMjudge's own compile script has to keep producing the wrapper it "
            'execs',
        )

    command = extension.compileCommand
    if command is None:
        commands = (
            language.compilation.commands if language.compilation is not None else None
        )
        if not commands:
            return None, 'language is not compiled'
        if len(commands) > 1:
            return (
                None,
                f'compilation.commands has {len(commands)} commands, and DOMjudge '
                'takes a single one',
            )
        command = commands[0]

    if '{compilable}' not in command or '{executable}' not in command:
        return (
            None,
            'the compilation command does not use both {compilable} and {executable}',
        )

    translated = command.replace('{executable}', '"$DEST"').replace(
        '{compilable}', '"$@"'
    )
    leftover = _PLACEHOLDER_RE.findall(translated)
    if leftover:
        return (
            None,
            f'the compilation command uses {", ".join(sorted(set(leftover)))}, which '
            'has no DOMjudge equivalent',
        )

    return (
        CompileScript(
            command=translated,
            script=_COMPILE_SCRIPT_TEMPLATE.format(
                name=language.name, command=translated
            ),
        ),
        None,
    )


def _plan_language(
    environment: Environment,
    language: EnvironmentLanguage,
    language_id: str,
    explicit: bool,
    server_by_id: Dict[str, Dict[str, Any]],
) -> LanguagePlan:
    extension = _language_extension(language)
    wanted = language_extensions(language)

    server_language = server_by_id.get(language_id)
    known = server_language is not None
    current = (
        [
            str(item).lstrip('.').lower()
            for item in (server_language.get('extensions') or [])
        ]
        if server_language is not None
        else []
    )
    # Union rather than replacement: narrowing a shared server's extension list
    # would reject submissions that work today, and rbx only needs its own files
    # to be accepted.
    added = [item for item in wanted if item not in current]
    compile_script, compile_skipped = build_compile_script(
        environment, language, extension
    )

    return LanguagePlan(
        name=language.name,
        language_id=language_id,
        explicit=explicit,
        known=known,
        added_extensions=added,
        all_extensions=[*current, *added],
        time_factor=extension.timeFactor,
        compile_script=compile_script,
        compile_skipped=compile_skipped,
    )


def build_plan(
    environment: Environment,
    server_languages: List[Dict[str, Any]],
    server_config: Dict[str, Any],
) -> Plan:
    """What to change on the server, given what it currently holds."""
    server_by_id = {
        str(language['id']): language
        for language in server_languages
        if language.get('id') is not None
    }

    planned: List[LanguagePlan] = []
    unmatched: List[str] = []
    seen: Dict[str, str] = {}

    for language in environment.languages:
        extension = _language_extension(language)
        extensions = language_extensions(language)

        if extension.languages:
            ids = [(language_id, True) for language_id in extension.languages]
        else:
            matched = match_by_extension(server_languages, extensions)
            ids = [(matched, False)] if matched is not None else []

        if not ids:
            unmatched.append(language.name)
            continue

        for language_id, explicit in ids:
            assert language_id is not None
            if language_id in seen:
                raise ValueError(
                    f'rbx languages `{seen[language_id]}` and `{language.name}` both '
                    f'map to the DOMjudge language `{language_id}`. Set '
                    '`extensions.domjudge.languages` on one of them to say which '
                    'DOMjudge language it really is.'
                )
            seen[language_id] = language.name
            planned.append(
                _plan_language(
                    environment, language, language_id, explicit, server_by_id
                )
            )

    preserved = [language_id for language_id in server_by_id if language_id not in seen]

    return Plan(
        languages=planned,
        preserved=preserved,
        unmatched=unmatched,
        config=_plan_config(environment, server_config),
    )


def _plan_config(
    environment: Environment, server_config: Dict[str, Any]
) -> List[ConfigChange]:
    extension = _environment_extension(environment)
    changes: List[ConfigChange] = []
    for field, key, factor in _CONFIG_KEYS:
        value = getattr(extension, field)
        if value is None:
            continue
        desired = value * factor
        current = server_config.get(key)
        if current == desired:
            continue
        changes.append(ConfigChange(key=key, current=current, desired=desired))
    return changes


def config_payload(changes: List[ConfigChange]) -> Dict[str, Any]:
    return {change.key: change.desired for change in changes}
