#!/bin/bash
# Runs INSIDE the jail: sources in /tmp/dir (read-only), input /tmp/in, output /tmp/out.
exec &>/tmp/stderrlog
cd /tmp/dir
# binfile.sh is generated by build-and-test.sh and is the only channel carrying the
# problem's limits into the jail. It defines BIN, MOJ_MEMLIMITMB and MOJ_STACKKB.
source binfile.sh

command -v pypy3 >/dev/null 2>&1 && exec pypy3 ./$BIN < /tmp/in > /tmp/out
exec python3 ./$BIN < /tmp/in > /tmp/out
