import collections
import pathlib
import shutil
from typing import Dict, List, Optional

import typer

from rbx import console, utils
from rbx.box import header, package
from rbx.box.dependencies import graph as deps_graph
from rbx.box.dependencies.amalgamation import AmalgamationError, amalgamate
from rbx.box.dependencies.scanner import DependencyKind
from rbx.box.packaging.moj_next import naming
from rbx.box.packaging.moj_next.extension import MojLanguageExtension
from rbx.box.packaging.moj_next.moj_language_utils import (
    get_emitted_moj_languages,
    get_moj_language_extension,
    get_moj_template_name,
)
from rbx.box.packaging.packager import BasePackager, BuiltStatement
from rbx.box.schema import CodeItem, ExpectedOutcome, ScoreType, Solution, TaskType
from rbx.box.statements.schema import StatementType
from rbx.config import get_default_app_path, get_testlib

# rbx has no author field, and MOJ hard-requires the file, so a visible placeholder
# keeps validate-problem.sh green until the setter fills it in on the server.
DEFAULT_AUTHOR = 'Unknown\n'

# The group name rbx reserves for samples. MOJ requires them to be named `sample*`,
# so this group alone is exempt from the testset prefix.
SAMPLES_GROUP = 'samples'

# No title (MOJ injects an <h1> from the server-side display_title), no examples (MOJ
# injects them from tests/input/sample*), and no fenced code blocks (a fence trips
# validate-problem.sh's hand-written-example warning). The two headings are mandatory.
DUMMY_STATEMENT = """Enunciado ainda não disponível.

## Entrada

A descrever.

## Saída

A descrever.
"""

# Fallback compilation flags per bundled template, used when the rbx language's `moj`
# extension does not set `flags`.
DEFAULT_FLAGS = {
    'c': '-std=gnu11 -O2 -lm -static',
    'cpp': '-std=c++20 -O2 -lm -static',
}

# Suffixes the amalgamator can reduce to a single translation unit.
_AMALGAMATABLE_SUFFIXES = {'.c', '.cc', '.cpp', '.cxx'}


class MojNextPackager(BasePackager):
    """Packager for the MOJ format as `mojtools` consumes it.

    Deliberately shares no code with the legacy `moj` packager. Two decisions shape
    everything else:

    - **Calibration-only time limits.** MOJ measures the limit by running every
      `sols/good` solution and scaling by `TLMOD[calibrafactor]`; it is never
      authored. So no `tl` is emitted and `conf` carries the only limit knobs.
    - **A single-file checker.** MOJ's bridge compiles `scripts/checker.cpp` with only
      `testlib.h` reachable, so the checker is amalgamated rather than shipped with
      its headers.
    """

    @classmethod
    def name(cls) -> str:
        return 'moj-next'

    @classmethod
    def task_types(cls) -> List[TaskType]:
        # MOJ's interactive support uses its own arbiter protocol (test in argv[1],
        # last stderr line `WRONG <reason>`, FIFO driver), not a testlib interactor.
        # The legacy `moj` packager still covers interactive problems.
        return [TaskType.BATCH]

    def statement_types(self) -> List[StatementType]:
        # MOJ's statement format is not supported by rbx yet; a dummy enunciado.md is
        # written instead, so no statement is built.
        return []

    # -- metadata -------------------------------------------------------------

    def _write_metadata(self, into_path: pathlib.Path) -> None:
        (into_path / 'author').write_text(DEFAULT_AUTHOR)
        (into_path / 'tags').write_text('')

        docs_path = into_path / 'docs'
        docs_path.mkdir(parents=True, exist_ok=True)
        (docs_path / 'enunciado.md').write_text(DUMMY_STATEMENT)

    def _write_conf(self, into_path: pathlib.Path) -> None:
        pkg = package.find_problem_package_or_die()
        lines = [
            '# Generated by rbx. Do not edit by hand.',
            '',
            '# Memory limit by measured peak RSS. Setting this also makes MOJ drop the',
            '# virtual-memory ulimit, which unfairly penalizes runtimes that reserve a',
            '# large heap without touching it, and feeds the JVM -Xmx via binfile.sh.',
            f'MEMLIMITMB={pkg.memoryLimit}',
            '',
            '# Output limit, in KB on both sides.',
            f'ULIMITS[-f]={pkg.outputLimit}',
            '',
            '# MOJ MEASURES the time limit; it is never authored. The judge runs every',
            '# sols/good solution, takes the worst time per language, and scales it by',
            '# this factor.',
            '# TODO(rbx): derive this from the authored timeLimit divided by the',
            '# measured model-solution runtime, so the calibrated limit lands near the',
            "# problem's own time limit instead of 1.35x the model solution.",
            'TLMOD[calibrafactor]=1.35',
            '',
        ]
        (into_path / 'conf').write_text('\n'.join(lines))

    # -- tests ----------------------------------------------------------------

    def _group_indices(self) -> Dict[str, int]:
        pkg = package.find_problem_package_or_die()
        return {group.name: index for index, group in enumerate(pkg.testcases)}

    def _write_tests(self, into_path: pathlib.Path) -> List[str]:
        """Write `tests/input` and `tests/output`; return the group names that got
        at least one test, in encounter order."""
        inputs_path = into_path / 'tests' / 'input'
        outputs_path = into_path / 'tests' / 'output'
        inputs_path.mkdir(parents=True, exist_ok=True)
        outputs_path.mkdir(parents=True, exist_ok=True)

        indices = self._group_indices()
        counters: Dict[str, int] = collections.defaultdict(int)
        seen_groups: List[str] = []
        has_sample = False

        for entry in self.get_built_testcase_entries():
            group_name = entry.group_entry.group
            if group_name not in counters:
                seen_groups.append(group_name)
            counters[group_name] += 1

            is_sample = entry.is_sample()
            has_sample = has_sample or is_sample
            name = naming.testcase_name(
                group_name,
                group_index=indices.get(group_name, 0),
                index=counters[group_name],
                is_sample=is_sample,
            )

            testcase = entry.metadata.copied_to
            shutil.copyfile(testcase.inputPath, inputs_path / name)
            if testcase.outputPath is not None:
                shutil.copyfile(testcase.outputPath, outputs_path / name)
            else:
                (outputs_path / name).touch()

        if not has_sample:
            console.console.print(
                '[error]This problem has no testcases in the [item]samples[/item] '
                'group, but MOJ requires at least one.[/error]\n'
                "[error]MOJ builds the statement's examples from "
                '[item]tests/input/sample*[/item], and [item]validate-problem.sh[/item] '
                'hard-fails a package without any.[/error]'
            )
            raise typer.Exit(1)

        return seen_groups

    def _write_score(self, into_path: pathlib.Path, seen_groups: List[str]) -> None:
        """Write `tests/score` for POINTS problems.

        BINARY problems get no score file: MOJ then scores by percentage of tests and
        still requires every one to pass, which is the correct ICPC semantics.
        """
        pkg = package.find_problem_package_or_die()
        if pkg.scoring != ScoreType.POINTS:
            return

        indices = self._group_indices()
        groups: List[naming.ScoreGroup] = []
        for group in pkg.testcases:
            # A group with no built tests would match nothing, and score-summary.sh
            # treats an unmatched group as "not executed", which can never be
            # Accepted. Skip it rather than poison the verdict.
            if group.name not in seen_groups:
                continue
            glob = (
                naming.SAMPLES_GLOB
                if group.name == SAMPLES_GROUP
                else naming.group_glob(group.name, indices[group.name])
            )
            groups.append(naming.ScoreGroup(glob=glob, weight=group.score))

        (into_path / 'tests' / 'score').write_text(naming.build_score_file(groups))

    # -- checker --------------------------------------------------------------

    def _builtin_header_roots(self) -> List[pathlib.Path]:
        """Directories holding the headers rbx injects beside a source.

        These are what make `testlib.h` and `rbx.h` inlinable; the amalgamator itself
        knows nothing about them.
        """
        return [get_testlib().parent, header.get_header().parent]

    def _amalgamate(self, code: CodeItem, what: str) -> bytes:
        try:
            result = amalgamate(
                utils.abspath(code.path), extra_roots=self._builtin_header_roots()
            )
        except AmalgamationError as e:
            console.console.print(
                f'[error]Cannot package {code.href()} for MOJ.[/error]\n'
                f'[error]{e}[/error]\n'
                f'[error]MOJ compiles the {what} from a single file, so it must '
                'reduce to one self-contained translation unit.[/error]'
            )
            raise typer.Exit(1) from e
        return result.content

    def _amalgamate_checker(self) -> bytes:
        checker = package.get_checker_or_builtin()
        if checker.path.suffix.lower() not in _AMALGAMATABLE_SUFFIXES:
            console.console.print(
                f'[error]Cannot package {checker.href()} for MOJ: the checker must be '
                'C++.[/error]\n'
                "[error]MOJ's checker bridge compiles [item]scripts/checker.cpp[/item] "
                'with g++ and knows no other language.[/error]'
            )
            raise typer.Exit(1)

        content = self._amalgamate_checker_content(checker)
        text = content.decode('utf-8', errors='replace')
        if 'quitp' in text or '_points' in text:
            console.console.print(
                '[warning]The checker references [item]quitp[/item]/'
                '[item]_points[/item], but MOJ maps a testlib partial result to a '
                'judge error, not to partial credit.[/warning]\n'
                '[warning]Express subtasks with [item]tests/score[/item] groups '
                'instead.[/warning]'
            )
        return content

    def _amalgamate_checker_content(self, checker: CodeItem) -> bytes:
        return self._amalgamate(checker, 'checker')

    def _write_checker(self, into_path: pathlib.Path) -> None:
        scripts_path = into_path / 'scripts'
        scripts_path.mkdir(parents=True, exist_ok=True)

        (scripts_path / 'checker.cpp').write_bytes(self._amalgamate_checker())

        # The compare driver runs on the judge HOST, where mojtools exists, so the
        # package ships the canonical stub rather than a copy of the bridge. A
        # bundled bridge copy is what spread one bwrap bug across 198 packages.
        stub_path = (
            get_default_app_path() / 'packagers' / 'moj_next' / 'scripts' / 'compare.sh'
        )
        compare_path = scripts_path / 'compare.sh'
        shutil.copyfile(stub_path, compare_path)
        # Without +x the judge gets "Permission denied" and every test is a judge error.
        compare_path.chmod(0o755)

    # -- solutions ------------------------------------------------------------

    def _tag_for(self, solution: Solution) -> Optional[str]:
        outcome = solution.outcome
        if outcome == ExpectedOutcome.ACCEPTED:
            return 'good'
        if outcome == ExpectedOutcome.ACCEPTED_OR_TLE:
            return 'pass'
        if outcome.is_slow():
            return 'slow'
        if outcome == ExpectedOutcome.ANY:
            return None
        return 'wrong'

    def _solution_content(self, solution: Solution) -> bytes:
        """The bytes to ship for a solution.

        A solution is compiled from a single file inside MOJ's jail, so a C/C++
        solution pulling in `rbx.h` or a local header gets the same amalgamation
        treatment as the checker. Other languages have no amalgamator, so a
        multi-file closure is an error rather than a package that fails to compile
        on the judge.
        """
        if solution.path.suffix.lower() in _AMALGAMATABLE_SUFFIXES:
            return self._amalgamate(solution, 'solution')

        graph = deps_graph.expand(solution, require_kind=DependencyKind.COMPILATION)
        if graph is not None and len(graph.nodes) > 1:
            deps = ', '.join(
                str(path)
                for path in sorted(graph.nodes)
                if path != package.get_relative_source_path(solution)
            )
            console.console.print(
                f'[error]Cannot package {solution.href()} for MOJ: it depends on '
                f'[item]{deps}[/item], but MOJ compiles a submission from a single '
                'file and rbx cannot amalgamate this language.[/error]'
            )
            raise typer.Exit(1)
        return solution.path.read_bytes()

    def _write_solutions(self, into_path: pathlib.Path) -> None:
        sols_path = into_path / 'sols'
        written: Dict[str, Dict[str, pathlib.Path]] = collections.defaultdict(dict)

        for solution in package.get_solutions():
            tag = self._tag_for(solution)
            if tag is None:
                console.console.print(
                    f'[warning]Skipping {solution.href()}: its expected outcome '
                    '[item]any[/item] does not map to a MOJ solution '
                    'directory.[/warning]'
                )
                continue

            basename = solution.path.name
            if basename in written[tag]:
                console.console.print(
                    f'[error]Cannot package for MOJ: {solution.href()} and '
                    f'[item]{written[tag][basename]}[/item] would both be written to '
                    f'[item]sols/{tag}/{basename}[/item].[/error]\n'
                    '[error]MOJ derives the language from the file name, and Java '
                    'requires it to match the public class, so rbx will not rename '
                    'them. Give one of them a different file name.[/error]'
                )
                raise typer.Exit(1)
            written[tag][basename] = solution.path

            dest_path = sols_path / tag / basename
            dest_path.parent.mkdir(parents=True, exist_ok=True)
            dest_path.write_bytes(self._solution_content(solution))

        if not written['good']:
            console.console.print(
                '[error]No accepted solution found, but MOJ needs at least one in '
                '[item]sols/good[/item].[/error]\n'
                '[error]MOJ measures the time limit by running them; a language with '
                'no accepted solution never gets one, and a package with none can '
                'never be calibrated.[/error]'
            )
            raise typer.Exit(1)

    # -- per-language scripts -------------------------------------------------

    def _write_language_scripts(self, into_path: pathlib.Path) -> None:
        scripts_path = into_path / 'scripts'
        scripts_path.mkdir(parents=True, exist_ok=True)
        templates_root = get_default_app_path() / 'packagers' / 'moj_next' / 'scripts'

        for language in get_emitted_moj_languages():
            template = get_moj_template_name(language)
            src_path = templates_root / template
            if not src_path.is_dir():
                console.console.print(
                    f'[warning]No MOJ script template [item]{template}[/item] for '
                    f'language [item]{language}[/item]; MOJ will fall back to its own '
                    f'[item]lang/{language}[/item] scripts.[/warning]'
                )
                continue

            dest_path = scripts_path / language
            shutil.copytree(src_path, dest_path, dirs_exist_ok=True)
            self._expand_language_vars(language, template, dest_path)

    def _expand_language_vars(
        self, language: str, template: str, dest_path: pathlib.Path
    ) -> None:
        extension: MojLanguageExtension = get_moj_language_extension(language)
        flags = extension.flags
        if flags is None:
            flags = DEFAULT_FLAGS.get(template, '')

        for path in dest_path.glob('**/*'):
            if not path.is_file():
                continue
            path.write_text(path.read_text().replace('{{rbxFlags}}', flags))
            if path.suffix == '.sh':
                # These run in the jail and are executed directly; without +x every
                # test is a judge error, and validate-problem.sh checks for it.
                path.chmod(0o755)

    # -- entry point ----------------------------------------------------------

    def package(
        self,
        build_path: pathlib.Path,
        into_path: pathlib.Path,
        built_statements: List[BuiltStatement],
    ) -> pathlib.Path:
        into_path.mkdir(parents=True, exist_ok=True)

        self._write_metadata(into_path)
        self._write_conf(into_path)
        seen_groups = self._write_tests(into_path)
        self._write_score(into_path, seen_groups)
        self._write_checker(into_path)
        self._write_solutions(into_path)
        self._write_language_scripts(into_path)

        shutil.make_archive(str(build_path / self.package_basename()), 'zip', into_path)
        return (build_path / self.package_basename()).with_suffix('.zip')
